In [1]:
#IMPORTING IMPORTANT LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from unidecode import unidecode
import warnings
import datetime
warnings.filterwarnings("ignore")

In [2]:
raw=pd.read_csv('fifa21 raw data v2.csv')
raw.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [3]:
#number of rows and columns
raw.shape

(18979, 77)

In [4]:
raw.describe()

,ID,Age,↓OVA,POT,BOV,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,226403.384794,25.194109,65.718636,71.136414,66.751726,248.938142,49.688392,45.842405,51.942726,58.768112,...,16.217187,16.519627,1595.286949,355.702197,67.453975,53.457031,57.681016,62.875020,49.866221,64.368934
std,27141.054157,4.710520,6.968999,6.114635,6.747193,74.299428,18.131153,19.567081,17.294409,14.519106,...,17.002239,17.854079,269.874789,40.761117,10.677859,13.827425,10.081857,9.927415,16.443213,9.601883
min,41.000000,16.000000,47.000000,47.000000,48.000000,42.000000,6.000000,3.000000,5.000000,7.000000,...,2.000000,2.000000,747.000000,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000
25%,210135.000000,21.000000,61.000000,67.000000,62.000000,222.000000,38.000000,30.000000,44.000000,54.000000,...,8.000000,8.000000,1452.000000,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000
50%,232418.000000,25.000000,66.000000,71.000000,67.000000,263.000000,54.000000,49.000000,55.000000,62.000000,...,11.000000,11.000000,1627.000000,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000
75%,246922.500000,29.000000,70.000000,75.000000,71.000000,297.000000,63.000000,62.000000,64.000000,68.000000,...,14.000000,14.000000,1781.000000,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000
max,259216.000000,53.000000,93.000000,95.000000,93.000000,437.000000,94.000000,95.000000,93.000000,94.000000,...,91.000000,90.000000,2316.000000,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000

In [5]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

In [6]:
#separating columns nto object and integer dtypes
object_cols = list(raw.select_dtypes(include=['object']).columns)
int_cols = list(raw.select_dtypes(include=['int']).columns)
print("Integer columns:", int_cols)

Integer columns: ['ID', 'Age', '↓OVA', 'POT', 'BOV', 'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats', 'Base Stats', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']

In [7]:
print("Object columns:", object_cols)

Object columns: ['Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Club', 'Contract', 'Positions', 'Height', 'Weight', 'Preferred Foot', 'Best Position', 'Joined', 'Loan Date End', 'Value', 'Wage', 'Release Clause', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'Hits']

# Here is a brief documentation for each column name in the given dataset
* photoUrl: The URL of the player's photo.
* LongName: The full name of the player.
* playerUrl: The URL of the player's page on sofifa.com.
* Nationality: The nationality of the player.
* Positions: The positions the player can play.
* Name: The short name of the player.
* Age: The age of the player.
* OVA: The overall rating of the player in FIFA 21.
* POT: The potential rating of the player in FIFA 21.
* Team & Contract: The team the player is playing for in FIFA 21, along with their contract details.
* ID: The unique identifier for the player.
* Height: The height of the player in feet and inches.
* Weight: The weight of the player in pounds.
* foot: The preferred foot of the player.
* BOV: The best overall rating the player has achieved in their career.
* BP: The best position the player has played in their career.
* Growth: The difference between the potential rating and overall rating of the player.
* Joined: The date the player joined their current team in FIFA 21.
* Loan Date End: The date the player's loan contract ends.
* Value: The market value of the player in FIFA 21.
* Wage: The weekly wage of the player in FIFA 21.
* Release Clause: The release clause value of the player in FIFA 21.
* Attacking: The attacking attributes of the player.
* Crossing: The crossing attribute of the player.
* Finishing: The finishing attribute of the player.
* Heading Accuracy: The heading accuracy attribute of the player.
* Short Passing: The short passing attribute of the player.
* Volleys: The volleys attribute of the player.
* Skill: The skill attributes of the player.
* Dribbling: The dribbling attribute of the player.
* Curve: The curve attribute of the player.
* FK Accuracy: The free kick accuracy attribute of the player.
* Long Passing: The long passing attribute of the player.
* Ball Control: The ball control attribute of the player.
* Movement: The movement attributes of the player.
* Acceleration: The acceleration attribute of the player.
* Sprint Speed: The sprint speed attribute of the player.
* Agility: The agility attribute of the player.
* Reactions: The reactions attribute of the player.
* Balance: The balance attribute of the player.
* Power: The power attributes of the player.
* Shot Power: The shot power attribute of the player.
* Jumping: The jumping attribute of the player.
* Stamina: The stamina attribute of the player.
* Strength: The strength attribute of the player.
* Long Shots: The long shots attribute of the player.
* Mentality: The mentality attributes of the player.
* Aggression: The aggression attribute of the player.
* Interceptions: The interceptions attribute of the player.
* Positioning: The positioning attribute of the player.
* Vision: The vision attribute of the player.
* Penalties: The penalties attribute of the player.
* Composure: The composure attribute of the player.
* Defending: The defending attributes of the player.
* Marking: The marking attribute of the player.
* Standing Tackle: The standing tackle attribute of the player.
* Sliding Tackle: The sliding tackle attribute of the player.
* Goalkeeping: The goalkeeping attributes of the player.
* GK Diving: The goalkeeper diving attribute of the player.
* GK Handling: The goalkeeper handling attribute of the player.
* GK Kicking: The goalkeeper kicking attribute of the player.
* GK Positioning: The goalkeeper positioning attribute of the player.
* GK Reflexes: This refers to the goalkeeper's ability to react and make saves quickly.
* Total Stats: This refers to the overall rating of the player based on their performance in all areas of the game.
* Base Stats: This refers to the player's rating in the six main areas of the game: Pace, Shooting, Passing, Dribbling, Defending, and Physicality.
* W/F: This refers to the player's weaker foot ability.
* SM: This refers to the player's skill moves ability. 
* A/W: This refers to the player's attacking work rate. It measures how frequently the player participates in attacking actions, such as making runs or positioning themselves in the opponent's half.
* D/W: This refers to the player's defensive work rate. It measures how frequently the player participates in defensive actions, such as tracking back or making tackles.
* IR: This refers to the player's injury resistance. It measures the player's ability to avoid injuries and how quickly they recover from them.
* PAC: This refers to the player's pace or speed attribute. It measures how quickly the player can move with and without the ball.
* SHO: This refers to the player's shooting ability. It measures the player's accuracy and power when shooting the ball.
* PAS: This refers to the player's passing ability. It measures the player's accuracy and range when passing the ball.
* DRI: This refers to the player's dribbling ability. It measures the player's agility, balance, and ball control when dribbling the ball.
* DEF: This refers to the player's defensive ability. It measures the player's ability to tackle, intercept, and defend against opposing players.
* PHY: This refers to the player's physicality or strength. It measures the player's ability to win physical battles and maintain possession of the ball. 
* Hits: This refers to the number of times the player's profile has been viewed on the website.

## Cleaning the data

Some conclusions after observing the data from some `object` type columns:  
1. Rename columns so it's easier to access them using dot notation (df.wage)
2. `Height` could be transformed to centimeters and converted to float
3. `Weight` can be converted to integer after removing lbs
4. `Foot` definitely must be converted to categorical
5. `Value` and `Release Clause` can be converted to float and remove euro sign (or maybe there's some dollar sign)
6. `W/F`, `SM` and `IR` must be converted to integer (or categorical and then ordered category)
7. `Joined` must be datetime dtype
8. `Hits` can be cleaned and transformed into integer 
9. Set `a/w` and `d/w` to categorical and sort their category values
10. Study `contract` column

#### Renaming columns

In [8]:
raw=raw.rename(columns={'↓OVA':'OVA'})

#### Working with duplicates

In [9]:
#duplicates
raw.duplicated().sum()

0

#### Missing values

In [10]:
raw.isnull().sum().sort_values(ascending=False)

Loan Date End       17966
Hits                 2595
GK Diving               0
Sliding Tackle          0
Standing Tackle         0
                    ...
Heading Accuracy        0
Finishing               0
Crossing                0
Attacking               0
Reactions               0
Length: 77, dtype: int64

In [11]:
#getting rid of the spaces ie \n\n...
raw = raw.replace(r'\n', '', regex=True)
raw.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,FC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,Juventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,Atlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,Manchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,Paris Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

Cleaning objects dtype columns

In [12]:
object_cols

['Name',
 'LongName',
 'photoUrl',
 'playerUrl',
 'Nationality',
 'Club',
 'Contract',
 'Positions',
 'Height',
 'Weight',
 'Preferred Foot',
 'Best Position',
 'Joined',
 'Loan Date End',
 'Value',
 'Wage',
 'Release Clause',
 'W/F',
 'SM',
 'A/W',
 'D/W',
 'IR',
 'Hits']

In [13]:
#cleaning long name column
t=set(''.join(raw['LongName'].tolist()))
t

{' ',
 "'",
 '-',
 '.',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '\xad',
 'À',
 'Á',
 'Â',
 'Å',
 'Ç',
 'É',
 'Í',
 'Ñ',
 'Ó',
 'Ö',
 'Ø',
 'Ü',
 'Þ',
 'ß',
 'à',
 'á',
 'â',
 'ã',
 'ä',
 'å',
 'æ',
 'ç',
 'è',
 'é',
 'ê',
 'ë',
 'í',
 'î',
 'ï',
 'ð',
 'ñ',
 'ò',
 'ó',
 'ô',
 'õ',
 'ö',
 'ø',
 'ú',
 'ü',
 'ý',
 'þ',
 'ā',
 'ă',
 'ą',
 'Ć',
 'ć',
 'Č',
 'č',
 'Đ',
 'đ',
 'ę',
 'ě',
 'ğ',
 'İ',
 'ı',
 'ķ',
 'Ľ',
 'ľ',
 'Ł',
 'ł',
 'ń',
 'ň',
 'Ō',
 'ō',
 'ő',
 'Ř',
 'ř',
 'Ś',
 'ś',
 'Ş',
 'ş',
 'Š',
 'š',
 'ū',
 'ů',
 'ź',
 'Ż',
 'ż',
 'Ž',
 'ž',
 'Ș',
 'ș',
 'Ț',
 'ț'}

In [14]:
#checking spellings of the names
na=raw[raw['LongName'].str.contains('[^a-zA-Z\s]', regex=True)]['LongName'].to_list()
na

['C. Ronaldo dos Santos Aveiro',
 'Neymar da Silva Santos Jr.',
 'Kylian Mbappé',
 'Marc-André ter Stegen',
 'Sadio Mané',
 'Sergio Ramos García',
 'Sergio Agüero',
 "N'Golo Kanté",
 'Samir Handanovič',
 'Trent Alexander-Arnold',
 'Fábio Henrique Tavares',
 'Pierre-Emerick Aubameyang',
 'Wojciech Szczęsny',
 'Ángel Di María',
 'Luka Modrić',
 'Luis Suárez',
 'Thomas Müller',
 'Raphaël Varane',
 'Gerard Piqué Bernabeu',
 'David Josué Jiménez Silva',
 'Alejandro Gómez',
 'Rodrigo Hernández Cascante',
 'Sergej Milinković-Savić',
 'Milan Škriniar',
 'Leroy Sané',
 'Clément Lenglet',
 'Marcos Aoás Corrêa',
 'Daniel Parejo Muñoz',
 'Jorge Resurrección',
 'Thiago Alcântara',
 'Péter Gulácsi',
 'Diego Godín',
 'Miralem Pjanić',
 'José María Giménez',
 'André Onana',
 'Lautaro Martínez',
 'Alejandro Grimaldo García',
 'Niklas Süle',
 'Raphaël Guerreiro',
 'Saúl Ñíguez Esclápez',
 'Nicolás Tagliafico',
 'Raúl Jiménez',
 'Marcelo Brozović',
 'Roman Bürki',
 'Josip Iličić',
 'José María Callejón Bueno',
 'Francisco Román Alarcón Suárez',
 'Jesús Corona',
 'César Azpilicueta Tanco',
 'Rui Pedro dos Santos Patrício',
 'Jesús Navas González',
 'Ousmane Dembélé',
 'Aaron Wan-Bissaka',
 'Marcos Acuña',
 'Martin Ødegaard',
 'Pau López Sabata',
 'Martin Dúbravka',
 'Gerard Moreno Balagueró',
 'Rafael A. Ferreira Silva',
 'Lucas Rodrigues M. Silva',
 'Filip Kostić',
 'José Luís Gayà Peña',
 'João Pedro Cavaco Cancelo',
 'Edin Višća',
 'Duván Zapata',
 'Mateo Kovačić',
 'Nélson Cabral Semedo',
 'Dušan Tadić',
 'Charles Aránguiz',
 'Aitor Fernández',
 'Lukáš Hrádecký',
 'Iker Muniain Goñi',
 'İlkay Gündoğan',
 'José Paulo Bezerra M. Júnior',
 'Edin Džeko',
 'Éver Banega',
 'Zlatan Ibrahimović',
 'João Filipe Moutinho',
 'Gonzalo Higuaín',
 'Lucas Hernández',
 'Dakonam Djené',
 'Jiří Pavlenka',
 'Josué Durval Chiamulera Vaz',
 'Nicolas Pépé',
 'Rúben Diogo da Silva Neves',
 'David Soria Solís',
 'Sergio Reguilón Rodríguez',
 'Andrej Kramarić',
 'Anderson Souza Conceição',
 'Ángel Correa',
 'Gerónimo Rulli',
 'Fabián Ruiz Peña',
 'Tomáš Vaclík',
 'Mário Figueira Fernandes',
 'Agustín Marchesín',
 'James Rodríguez',
 'Danilo Luís Hélio Pereira',
 'Álvaro Borja Morata Martín',
 'Sergio Asenjo Andrés',
 'Raúl Albiol Tortajada',
 'Mesut Özil',
 'Ivan Rakitić',
 'Marko Arnautović',
 'Jérôme Boateng',
 'Ivan Perišić',
 'Rúben Santos Gato Alves Dias',
 'Ferran Torres García',
 'João Félix Sequeira',
 'Josef Martínez',
 'Rosberto J. Dourado Santos',
 'Welington Kauê Dano Nascimento',
 'Tomáš Souček',
 'Marko Dmitrović',
 'Ander Capa Rodríguez',
 'Naby Keïta',
 'Iñaki Williams Arthuer',
 'Davinson Sánchez',
 'Ignacio Fernández',
 'Joaquín Correa',
 'Walter Benítez',
 'Moussa Dembélé',
 'Gonçalo Manuel Ganchinho Guedes',
 'Jordi Masip López',
 'Sebastián Coates',
 'Antonio Rüdiger',
 'Stefan Savić',
 'Jesús Joaquín Fernández Sáez',
 'Francisco Alcácer García',
 'Pablo Sarabia García',
 'Sébastien Haller',
 'Ismaily Gonçalves dos S.',
 'Andrés Iniesta Luján',
 'Mario Götze',
 'Javier Martínez Aginaga',
 'Iván Marcano Sierra',
 'Marek Hamšík',
 'Stéphane Ruffier',
 'Łukasz Fabiański',
 'Franck Ribéry',
 'Héctor Herrera',
 'Képler Laveran Lima Ferreira',
 'André-Pierre Gignac',
 'Jaime Nicolás Frendado',
 'Vinícius José de Oliveira Júnior',
 'Maximiliano Gómez',
 'Dominik Livaković',
 'Mauro Evidio Nérez',
 'Matías David Baldona',
 'Saúl Marcelo Ardero',
 'Luis Roberto Dálves',
 'José María Sildero',
 'Çağlar Söyüncü',
 'Éder Gabriel Militão',
 'Unai Simón Mendibil',
 'Theo Hernández',
 'Luka Jović',
 'Segundo Mandíquez',
 'Yeray Álvarez López',
 'Daniel Ceballos Fernández',
 'Mikel Merino Zazón',
 'Allan Saint-Maximin',
 'Héniton Enaldo Pires Tramontino',
 'Diogo José Teixeira da Silva',
 'Nicolò Barella',
 'Otávio Edmilson da Silva Monteiro',
 'Victor Lindelöf',
 'José Ángel Esmoris Tasende',
 'Piotr Zieliński',
 'Pierre-Emile Højbjerg',
 'Lucas Vázquez Iglesias',
 'Rubén Peña Jiménez',
 'João Mário Naval Costa Eduardo',
 'Iñigo Martínez Berridi',
 'Nikola Vlašić',
 'Šime Vrsaljko',
 'José Gómez Campaña',
 'José Ignacio Fernández Iglesias',
 'Gerard Deulofeu Lázaro',
 'Adem Ljajić',
 'Jérôme Roussillon',
 'Pavel Kadeřábek',
 'Héctor Bellerín Moruno',
 'Damián Suárez',
 'Cédric Bakambu',
 'Benjamin André',
 'Mario Gaspar Pérez Martínez',
 'Willian José da Silva',
 'Enzo Pérez',
 'André Gomes Magalhães Almeida',
 'Nemanja Matić',
 'João Miranda de Souza Filho',
 'Antonio Adán Garrido',
 'Branislav Ivanović',
 'Simon Kjær',
 'Łukasz Piszczek',
 'Alexis Sánchez',
 'Bafétimbi Gomis',
 'Raúl García Escudero',
 'Radamel Falcao García Zarate',
 'Mousa Dembélé',
 'Pedro Rodríguez Ledesma',
 'Luís Carlos Almeida da Cunha',
 'Joaquín Sánchez Rodríguez',
 'Leandro Miguel Sáreda',
 'Aluísio Chaves Rib. Moraes Júnior',
 'Enzo Martín Riquero',
 'Edgar Manuel Guichón',
 'Carlos Vinícius Alves Morais',
 'Dan-Axel Zagadou',
 'Predrag Rajković',
 'Jules Koundé',
 'Héctor Junior Firpo Adamés',
 'Nemanja Maksimović',
 'Pervis Estupiñán',
 'Jonathan Ikoné',
 'Carlos Soler Barragán',
 'Álvaro Odriozola Arzalluz',
 'Luan Vágner Boas Macedo',
 'Bernard Gabriel Prestão Chaves',
 'Melvin Luan Parrela Porfírio',
 'André Miguel Valente da Silva',
 'Ezequiel Ávila',
 'Léo Dubois',
 'Hamari Traoré',
 'Duje Ćaleta-Car',
 'Joan Jordán Moreno',
 'Cristian Pavón',
 'Tiemoué Bakayoko',
 'Dominic Calvert-Lewin',
 'Joseba Zaldúa Bengoetxea',
 'Ante Rebić',
 'Adama Traoré Diarra',
 'João Paulo Dias Fernandes',
 'José Luis Morales Nogales',
 'Daniel García Carrillo',
 'Ayoze Pérez Gutiérrez',
 'Darío Benedetto',
 'José Pedro Malheiro de Sá',
 'André Filipe Tavares Gomes',
 'Rubén García Santos',
 'Édouard Mendy',
 'Nicolás Otamendi',
 'Nathan Aké',
 'Omar Mascarell González',
 'Hakan Çalhanoğlu',
 'Matheus Lima Magalhães',
 'Luka Milivojević',
 'James Ward-Prowse',
 'Mário Rui Silva Duarte',
 'André Carrillo',
 'Álvaro González Soberón',
 'Pedro León Sánchez Gil',
 'Ibai Gómez Pérez',
 'Rafael Alcântara',
 'Aïssa Mandi',
 'Víctor Machín Pérez',
 'Nicolás Lodeiro',
 'Lucas Pérez Martínez',
 'João Pedro G. Santos Galvão',
 'Alex Oxlade-Chamberlain',
 'Jaume Vicent Costa Jordá',
 'Fabián Orellana',
 'Salif Sané',
 'Ander Herrera Agüera',
 'José Ángel Valdés Díaz',
 'Gylfi Sigurðsson',
 'Sidnei Rechel da Silva Júnior',
 'Vedran Ćorluka',
 'Séamus Coleman',
 "Yann M'Vila",
 'Ángel Luís Rodríguez Díaz',
 'Juan Manuel Mata García',
 'Marcelo Díaz',
 'Nahuel Guzmán',
 'Kévin Gameiro',
 'Benoît Costil',
 'José Manuel Reina Páez',
 'Márcio Rafael Ferreira de Souza',
 'Éder Citadin Martins',
 'Vladimír Coufal',
 'Francisco Mota Castro Trincão',
 'Daniel Martín Lenzado',
 'Bruno Guimarães Moura',
 'Sebastián Bruno Luna',
 'Luís Manuel Arantes Maximiano',
 'Ondřej Kolář',
 'Lisandro Martínez',
 'Lorenzo Morón García',
 'Luis Díaz',
 'Unai Núñez Gestoso',
 'Óscar Melendo Jiménez',
 'Ibrahima Konaté',
 'Matías Rojas',
 'Cengiz Ünder',
 'Gabriel dos S. Magalhães',
 'Miguel Almirón',
 'Renato Júnior Luz Sanches',
 'Fabian Schär',
 'Ismaïla Sarr',
 'Fred Claudinei Tófoli Vilela',
 'Arturo Adolfo Inálcio Dutra',
 'G. Pierre Paiva Souza',
 'Everton Jorge Simão Resende',
 'A. Benjamin Chiamuloira Paes',
 'Wellingt. Edson Sabrão Rolim',
 'Gérson Adriano Gutierres Serra',
 'Pierre Lees-Melou',
 'João Maria Palhinha Gonçalves',
 'Benjamin Verbič',
 'Jonathan Rodríguez',
 'Krzysztof Piątek',
 'Karl Toko-Ekambi',
 'Jaume Domenech Sánchez',
 'Jonathan Rodríguez Menéndez',
 'Jean-Pierre Nsame',
 'Rafael Santos Borré',
 'Ángel Mena',
 'Nuno Miguel Jerónimo Sequeira',
 'Iván Marcone',
 'Jean-Philippe Gbamin',
 'Ruben Loftus-Cheek',
 "Jack O'Connell",
 'José Ignacio Martínez García',
 'Darwin Machís',
 'Raúl de Tomás Gómez',
 'Jhon Córdoba',
 'Youssef En-Nesyri',
 'Miguel Ángel Moyá Rumbo',
 'Sead Kolašinac',
 'Burak Yılmaz',
 'Romain Saïss',
 'Abdoulaye Doucouré',
 'Manuel Trigueros Muñoz',
 'Leonardo Carrilho Baptistão',
 'Téji Savanier',
 'Bernard Anício Caldeira Duarte',
 'Filip Novák',
 'Denis Suárez Fernández',
 'Jan Bořil',
 'Emiliano Martínez',
 'Younès Belhanda',
 'Djibril Sidibé',
 'Ciprian Tătărușanu',
 'Kévin Malcuit',
 'Fredrik Midtsjø',
 "M'Baye Niang",
 'Martin Škrtel',
 'Christian Günter',
 'Celso Ortíz',
 'Ștefan Radu',
 'Sérgio Miguel Relvas de Oliveira',
 'Víctor Laguardia Cisneros',
 'Germán Pezzella',
 'Ricardo Rodríguez',
 'Iago Herrerín Buisán',
 'Luis Rodríguez',
 'Kevin-Prince Boateng',
 'Senad Lulić',
 'Matías Suárez',
 'Víctor David Díaz Miguel',
 'Carlos Tévez',
 'José Sosa',
 'Andrés Eduardo Fernández Moreno',
 'José Miguel da Rocha Fonte',
 'Andrés Guardado',
 'Lisandro López',
 'Gastón Ramírez',
 'Lucas Luciano Mantela Patrício',
 'Mario Pašalić',
 'Franck Yannick Kessié',
 'Federico Fernández',
 'Manuel H. Tavares Fernandes',
 'Claudio Nuno Coíntra Calegari',
 "Danilo D'Ambrosio",
 'Rafał Gikiewicz',
 'Adam Marušić',
 'Sidney Adrián Pessoa Vidigal',
 'Aridane Hernández Umpiérrez',
 'Iván Cuéllar Sacristán',
 'Salomón Rondón',
 'Ricardo Centurión',
 'Ralf Fährmann',
 'Antonio José Rodríguez Díaz',
 'Stevan Jovetić',
 'Vladimír Darida',
 'Mikel San José Domínguez',
 'Fransérgio Rodrigues Barbosa',
 'Rúben Miguel Nunes Vezo',
 'Rubén Duarte Sánchez',
 'Vicente Damián Castro',
 'Nikola Kalinić',
 'Martín Montoya Torralbo',
 'Germán Sánchez Barahona',
 'Régis Gurtner',
 'Cláudio Pires de Morais Ramos',
 'Franco Vázquez',
 'Jóhann Berg Guðmundsson',
 'Miguel Luís Pinto Veloso',
 'Antonio Villa Suárez',
 'Mathías Olivera',
 'Fábio Santos Martins',
 'Roger Martí Salvador',
 'Yimmi Chará',
 'Héctor Moreno',
 'Óliver Torres Muñoz',
 'Iñigo Córdoba Kerejeta',
 'Gonçalo Mendes Paciência',
 'Joël Veltman',
 'Emiliano Buendía',
 'Sebastián Blanco',
 'Sergio Rico González',
 'Rubén Alcaraz Jiménez',
 'Mert Günok',
 'Sergi Gómez Solà',
 'Raúl Ruidíaz',
 'Jadson José Meireles Correia',
 'Max-Alain Gradel',
 'Bruno Petković',
 'Krépin Diatta',
 'Cheikhou Kouyaté',
 'Jefferson Farfán',
 'Enrique García Martínez',
 'Nikola Maksimović',
 'Jérémie Boga',
 'Javier Hernández',
 'Rubén Rochina Naixes',
 'Unai López Cabrera',
 'Víctor Ruiz Torre',
 'Elías Hernández',
 'Andeson Jaime Trigo Gonçalves',
 'Mariano Díaz Mejía',
 'André-Franck Zambo Anguissa',
 'Aleksandar Mitrović',
 'Marc Roca Junqué',
 'Zeki Çelik',
 'José Pedro Fuenzalida',
 'Alexander Sørloth',
 'Pedro Filipe Teodósio Mendes',
 'Oier Sanjurjo Maté',
 'Okay Yokuşlu',
 'Nicolás De la Cruz',
 'Ángel Montoro Sánchez',
 'Iago Falqué Silva',
 'Pedro António Pereira Gonçalves',
 'Leandro Agustín Baezo',
 'Nahitan Nández',
 'Matija Nastasić',
 'Jorge Sandro Herrería',
 'Otávio Henrique Passos Santos',
 'Moisés Gómez Bordonado',
 'Alberto Moreno Pérez',
 'Uğurcan Çakır',
 'Clinton Mukoni Mata Pedro Lourenço',
 'Benjamin Hübner',
 'Dodi Lukébakio',
 'Mattéo Guendouzi',
 'Rafael Tolói',
 'Rodrigo Éder Vuarte Ruiz',
 'Saïd Benrahma',
 'Danilo Manuel Vieira Espíndola',
 'José Luís Mendes Andrade',
 'David López Silva',
 'Marin Pongračić',
 'Alfreð Finnbogason',
 'Sergio Herrera Pirón',
 'Derlis González',
 'Niclas Füllkrug',
 'Loïc Rémy',
 'Vadis Odjidja-Ofoe',
 'Javier Manquillo Gaitán',
 'Álvaro Negredo Sánchez',
 'Leonardo Fernández',
 'Maximilian Mittelstädt',
 'Simão Alvin Acunha Bardini',
 'Andrés Daniel Píriz',
 'Lúcio Anselmo Corteijo Salazar',
 'David García Zubiria',
 'Diego Castro Giménez',
 'Lisandro López',
 'Gabriel Jairo Aníbal Rangel',
 'Diego López Rodríguez',
 'Aurélio Gabriel Ulineia Buta',
 'Florentino Morris Luís',
 'Carlos Clerc Martínez',
 'Bertrand Traoré',
 'José Diogo Dalot Teixeira',
 'Gaël Kakuta',
 'Soualiho Meïté',
 'Nicolás Gaitán',
 'Florian Müller',
 'Jean-Paul Boëtius',
 'Gökhan Gönül',
 'Mauro Zárate',
 'Hernán Pérez',
 'Fernando Marçal de Oliveira',
 'Santiago García',
 'Carlos Fernández Luna',
 'Gaëtan Laborde',
 'Lucas Martínez Quarta',
 'Gonzalo Martínez',
 'Davy Pröpper',
 'İrfan Can Kahveci',
 'Diego Javier Llorente Ríos',
 'Raúl Michel Melo da Silva',
 'Yeimar Gómez Andrade',
 'Luis Mejía',
 'Andraž Šporar',
 'José Luis Palomino',
 'Marcelo Antônio Guedes Filho',
 'Joel Robles Blázquez',
 'Jesús Vallejo Lázaro',
 'Jean Michaël Seri',
 'Ermin Bičakčić',
 'Guido Rodríguez',
 'Manuel Agudo Durán',
 'José Luis Sanmartín Mato',
 'Zlatko Junuzović',
 'Diadie Samassékou',
 'Erick Sebastião Laforte Medeiros',
 'Frédéric Guilbert',
 'Matías Zaracho',
 'Ömer Toprak',
 'Jean-Philippe Mateta',
 'Rubén Blanco Veiga',
 'Francisco Femenía Far',
 'Nicolò Zaniolo',
 'Agustín Rossi',
 'José Carlos Gonçalves Rodrigues',
 'Fred Marcos Aníbal Dias',
 'Uílson de Souza Paula Júnior',
 'Karl-Johan Johnsson',
 'Cédric Ricardo Alves Soares',
 'Darko Lazović',
 'Óscar Murillo',
 'Pierre Tomás Torres De Faria',
 'André Ayew',
 'Joakim Mæhle',
 'Matías Kranevitter',
 'Óscar Romero',
 'Hernâni Jorge Santos Fortes',
 'Darko Brašanac',
 'Boubakary Soumaré',
 'Gabriel Vasconcelos F.',
 'Francisco L. Lima Silva Machado',
 'Daniel Filipe Martins Carriço',
 'Francisco Mérida Pérez',
 'Tomás Pina Isla',
 'Martín Cáceres',
 'Luis Quiñones',
 'Yusuf Yazıcı',
 'Nicolás Evandro Filheiro Stein',
 'Luiz Araújo',
 'Adrián San Miguel Castillo',
 'Pascal Groß',
 'Santiago Ascacíbar',
 'Frederik Rønnow',
 'Óscar Opazo',
 'Youssouf Koné',
 'Kevin Stöger',
 'Mislav Oršić',
 'Adrien S. Perruchet Silva',
 'Gustavo Cuéllar',
 'Paulo André Rodrigues Oliveira',
 'Petr Ševčík',
 'Ainsley Maitland-Niles',
 'Nery Domínguez',
 'Jesús Gallardo',
 'Óscar Plano Pedreño',
 'Jorge Miramón',
 'Rômulo Borges Monteiro',
 'Łukasz Skorupski',
 'Lucas Zelarayán',
 'Antonio García Aranda',
 'Tomasz Kędziora',
 'Eduardo Expósito Jaén',
 'Keita Baldé',
 'Juan Miguel Jiménez López',
 'Fábio José Ferreira Pacheco',
 'Jorge Hernández',
 'Uroš Račić',
 'Gastón Silva',
 'Abdoulaye Touré',
 'Pascoal Simão Muscato Vieira',
 'Habib Maïga',
 'Jorge Sánchez',
 'Eric Maxim Choupo-Moting',
 'Augusto Fernández',
 'Ramón Azeez',
 'Fayçal Fajr',
 'Pape Abou Cissé',
 'Lasse Schøne',
 'Lovre Kalinić',
 'Hugo González',
 'Duirval Hélton Diniz Cabral',
 'Martín Merquelanz',
 'Tamás Kádár',
 'Bořek Dočkal',
 'Graziano Pellè',
 'Murilo Kauê Cadete Teixeira',
 'Jorge Andújar Moreno',
 'Dimitri Liénard',
 'Oğuzhan Özyakup',
 'Robert Berić',
 'Kaíqundo Calado Dimas',
 'Yony González',
 'Edson Álvarez',
 'Christophe Hérelle',
 'Moussa Niakhaté',
 'André Filipe Luz Horta',
 'Vedad Ibišević',
 'Osmar Ibañez Barba',
 'Nuri Şahin',
 'Orkun Kökçü',
 'Nicolas De Préville',
 'Gastón Pereiro',
 'Ismaël Traoré',
 'Aarón Martín Caricol',
 'Nikola Milenković',
 'Guillermo Maripán',
 'Bruno Vinícius Souza Ramos',
 'Cristian Álvarez',
 'Wilson Miguéis Manafá Jancó',
 'Sebastián Fernández',
 'Édson Puch',
 'Matías Dituro',
 'Pablo Marí Villar',
 'Lukáš Masopust',
 'Francisco José Olivas Alba',
 'Nicolás Vikonis',
 'Pablo Nicolás Dárenas',
 'Diego Chará',
 'Jesús Dueñas',
 'Daniel Muñoz',
 'Diego Aaron Pámanes',
 'Francesc Fàbregas i Soler',
 'Yūya Ōsako',
 'Tomás Rincón',
 'Dídac Vilà Roselló',
 'Olívio Da Rosa',
 'Estevão Danilo Candeira Inácio',
 'Antonio Martínez López',
 'Ramón Ábila',
 'José Sand',
 'Georges-Kévin Nkoudou',
 'Uroš Spajić',
 'Rúben Barcelos De Sousa Lameiras',
 'Kyle Walker-Peters',
 'Yoel Rodríguez Oterino',
 'Serkan Kırıntılı',
 'Christian Kouamé',
 'Filip Đuričić',
 'Mateus Tetê',
 'Nikola Vukčević',
 'César Montes',
 'Adrià Giner Pedrosa',
 'Fernando Gorriarán',
 'Abdülkadir Ömür',
 'Domagoj Bradarić',
 'Miguel Ângelo da Silva Rocha',
 'Sergio Otálvaro',
 'Carlos Rodríguez',
 'Estevão Daniel Formoso Serpa',
 'Wuilker Faríñez',
 'Emilio Alex Piodão Esser',
 'Fabián Castillo',
 'Mariano Bíttolo',
 'Joelinton Apolinário de Lira',
 'Ibrahima Traoré',
 'Unai Bustinza Martínez',
 'Saphir Taïder',
 'Fabián Rinaudo',
 'Roberto Jiménez Gago',
 'Leôncio Roger Vimieiro Madeira',
 'Javier Eraso Goñi',
 'Nélson Miguel Castro Oliveira',
 'Ionuț Andrei Radu',
 'Iván Pillud',
 'Fabián Balbuena',
 'Aleksandar Dragović',
 'Haris Seferović',
 'Ricard Puig Martí',
 'Néstor Araújo',
 'Paweł Kieszek',
 'Alexander Nübel',
 'Emre Kılınç',
 'Luis Miguel Rodríguez',
 'Éder Balanta',
 'Jean-Clair Todibo',
 'Miguel Layún',
 'Pablo Hernández',
 'Zainadine Chavango Júnior',
 'Tiago Miguel Baía Pinto',
 'Martín Aguirregabiria',
 'Nicolás Domingo',
 'José Juan Macías',
 'Joshua Eduardo Sá Madeira',
 'Marko Grujić',
 'Sergiño Dest',
 'Jeff Reine-Adélaïde',
 'Bruno Pittón',
 'Lago Júnior',
 'Frederico André Ferrão Venâncio',
 'Henry Martín',
 'Cristian Also Laranjeiro Sá',
 'Luis Javier Suárez',
 'Javairô Dilrosun',
 'Armindo Tué Na Bangna',
 'Brais Méndez Portela',
 'Asmir Begović',
 'Ángel Romero',
 'João Victor Santos Sá',
 'Hasan Ali Kaldırım',
 'Alexandru Mitriță',
 'Kaíque Osvaldo Castro Rodrigues',
 'Gastón Giménez',
 'Alexis Claude-Maurice',
 'Ismaël Bennacer',
 'Hernani Azevedo Júnior',
 'Arthur Mendonça Cabral',
 'Nehuén Pérez',
 'François Kamano',
 'Javier García Fernández',
 'Andrés Cubas',
 'Enes Ünal',
 'Francisco José Beltrán Peinado',
 'Diogo António Cupido Gonçalves',
 'Matías Vargas',
 'João Carlos Vilaça Teixeira',
 'Federico Viñas',
 'Borja García Freire',
 'André Filipe Brás André',
 'Rúben Afonso Borges Semedo',
 'Kodjo Fo-Doh Laba',
 'Hervé Koffi',
 'Luís Carlos Novo Neto',
 'Nicolás González',
 'Rémi Oudin',
 'Adrián Embarba Blazquez',
 'Dorlan Pabón',
 'Peter Pekarík',
 'Mama Samba Baldé',
 'Juan Gabriel Rodríguez',
 'Daniel Rodríguez Vázquez',
 'Nicolás Domínguez',
 'José de Jesús Corona',
 'Facundo Sánchez',
 'Manuel García Sánchez',
 'Pablo Hernández Dominguez',
 'Adrián López Álvarez',
 'Sebastián Villa',
 'Óscar Rodríguez Arnaiz',
 'Sebastián Córdova',
 'Deniz Türüç',
 'Rubén Sobrino Pozuelo',
 'Bartłomiej Drągowski',
 'Jesus Fabrício Andrade Simões',
 'Juan Sánchez Miño',
 'Mateo Pavlović',
 'Andrés Ricaurte',
 'Antonín Barák',
 'Albert Rusnák',
 'Marius Müller',
 'Sergio Álvarez Díaz',
 'Felipe Gutiérrez',
 'Bruno González Cabrera',
 'Ron-Robert Zieler',
 'Almamy Touré',
 'Jeremiah St. Juste',
 'Théo Bongonda',
 'Romário Ricardo da Silva',
 'Edvaldo Flávio Rebelo de Freit',
 'Mario Suárez Mata',
 'Bradley Wright-Phillips',
 'Iván Alejo Peralta',
 'Diogo José Figueiras',
 'Nicholas Júlio Aldair Leal',
 'Héctor Villalba',
 'Răzvan Marin',
 'Murilo Kaíque Sanches Cardoso',
 'Manuel Vallejo Galván',
 'Marc-Oliver Kempf',
 'Mehdi Carcela-González',
 'Toma Bašić',
 'Álvaro Vadillo Cifuentes',
 'João Pedro Barradas Novais',
 'Salvador Sánchez Ponce',
 'Gustavo Enrique Assunção da Silva',
 'Iván Sánchez Aguayo',
 'Nicolai Müller',
 'Sebastián Cristóforo',
 'Juan José Santigaro',
 'Orbelín Pineda',
 'Júlio César Pires Feitosa',
 'Richard Sánchez',
 'Gleidionor Júnior',
 'Ömer Ali Şahiner',
 'Núrio Domingos Matias Fortuna',
 'Gilberto Moraes Júnior',
 'Teófilo Gutiérrez',
 'Fabricio Agosto Ramírez',
 'Valère Germain',
 'Miloš Ninković',
 'Rodrigo Éder Serpa Conceição',
 'Lamine Koné',
 'José Izquierdo',
 'Roger Assalé',
 'Klaas-Jan Huntelaar',
 'Vinicius Lúcio Cardenha Caeiro',
 'Patrik Hrošovský',
 'Gabriel Moisés Antunes da Silva',
 'Gökhan Töre',
 'Rafael da Conceição Leão',
 'Sergio León Limones',
 'Cican Stanković',
 'Bruno Ecuélé Manga',
 'Ole Kristian Selnæs',
 'José Emerson Mirazar Coelho',
 'Nazim Sangaré',
 'Diego Mariño Villar',
 'Guillermo Fernández',
 'Ailton Sérgio Guevara Muscato',
 'Alejandro Fernández Iglesias',
 'João Pedro da Silva Pereira',
 'Ondřej Kúdela',
 'Víctor Rodríguez Romero',
 'André Luís Gomes Simões',
 'Estevão Danilo Baldeiro Lopes',
 'Jasmin Kurtić',
 'Iñigo Pérez Soto',
 'Jürgen Locadia',
 'Maxime Barthelmé',
 'Radim Řezník',
 'André Ramalho Silva',
 'Cecilio Domínguez',
 'Jérémy Morel',
 'Otávio Alberto Cairinho Monteiro',
 'Timothée Kolodziejczak',
 'Daniel Congré',
 'Lukáš Kalvach',
 'Ibrahim Traoré',
 'Adam Hložek',
 'Ramón Samuel da Almeyda Aníbal',
 'Elias Gómez',
 'Éder Macedo Lopes',
 'Callum Hudson-Odoi',
 'Papiss Demba Cissé',
 'Braian Cufré',
 'Oier Olazábal Paredes',
 'Stéphane Sessègnon',
 'Jakub Błaszczykowski',
 'Jeremías Conan Ledesma',
 'Vlad Chiricheș',
 'Loïc Négo',
 'Andrés Felipe Roa',
 'Kévin Manuel Rodrigues',
 'Enrique González Casín',

In [15]:
#removing those special characters
raw['LongName']=raw['LongName'].apply(lambda x: unidecode(x))
raw['LongName']

0                        Lionel Messi
1        C. Ronaldo dos Santos Aveiro
2                           Jan Oblak
3                     Kevin De Bruyne
4          Neymar da Silva Santos Jr.
                     ...
18974                          Ao Xia
18975                       Ben Hough
18976                  Ronan McKinley
18977                    Zhen'ao Wang
18978                       Xiao Zhou
Name: LongName, Length: 18979, dtype: object

In [16]:
#cleaning naionality column
s=set(''.join(raw['Nationality'].tolist()))
raw[raw['Nationality'].str.contains('[^a-zA-Z\s]', regex=True)]['Nationality'].to_list()

['Trinidad & Tobago',
 'Trinidad & Tobago',
 'Antigua & Barbuda',
 'São Tomé & Príncipe',
 'Trinidad & Tobago',
 'Trinidad & Tobago',
 'Antigua & Barbuda',
 'Antigua & Barbuda',
 'Trinidad & Tobago',
 'Antigua & Barbuda',
 'Trinidad & Tobago']

In [17]:
#cleaning club column
raw['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City',
       'Paris Saint-Germain', 'FC Bayern München', 'Liverpool',
       'Real Madrid', 'Chelsea', 'Tottenham Hotspur', 'Inter', 'Napoli',
       'Borussia Dortmund', 'Manchester United', 'Arsenal', 'Lazio',
       'Leicester City', 'Borussia Mönchengladbach', 'Real Sociedad',
       'Atalanta', 'Olympique Lyonnais', 'Milan', 'Villarreal CF',
       'RB Leipzig', 'Cagliari', 'Ajax', 'SL Benfica', 'AS Monaco',
       'Wolverhampton Wanderers', 'Everton', 'Fiorentina', 'FC Porto',
       'RC Celta', 'Torino', 'Sevilla FC', 'Grêmio', 'Real Betis', 'Roma',
       'Newcastle United', 'Eintracht Frankfurt', 'Valencia CF',
       'Medipol Başakşehir FK', 'Inter Miami', 'Bayer 04 Leverkusen',
       'Levante UD', 'Crystal Palace', 'Athletic Club de Bilbao',
       'Shanghai SIPG FC', 'VfL Wolfsburg',
       'Guangzhou Evergrande Taobao FC', 'Al Shabab',
       'Olympique de Marseille', 'Los Angeles FC',
       'Beijing Sinobo Guoan FC', 'Getafe CF', 'SV Werder Bremen',
       'TSG 1899 Hoffenheim', 'LOSC Lille', 'Deportivo Alavés', 'Burnley',
       'Leeds United', 'Fulham', 'PFC CSKA Moscow', 'Genoa',
       'Galatasaray SK', 'Atlanta United', 'Atlético Mineiro', 'Flamengo',
       'Palmeiras', 'No Club', 'São Paulo', 'West Ham United', 'SD Eibar',
       'River Plate', 'OGC Nice', 'Real Valladolid CF', 'Sporting CP',
       'PSV', 'Feyenoord', 'Club Brugge KV', 'Shakhtar Donetsk',
       'Vissel Kobe', 'Boca Juniors', '1. FC Union Berlin',
       'Dalian YiFang FC', 'AS Saint-Étienne', 'Sassuolo',
       'Tigres U.A.N.L.', 'Dinamo Zagreb', 'Dynamo Kyiv', 'Fluminense',
       'Udinese', 'Aston Villa', 'Stade Rennais FC', 'Beşiktaş JK',
       'Brighton & Hove Albion', 'Hebei China Fortune FC', 'Southampton',
       'Lokomotiv Moscow', 'Jiangsu Suning FC', 'Al Hilal',
       'West Bromwich Albion', 'Fenerbahçe SK', 'FC Groningen',
       'Guangzhou R&F FC', 'Orlando City SC', 'Sampdoria',
       'Stade de Reims', 'Sheffield United', 'Santos', 'Internacional',
       'Coritiba', 'CA Osasuna', 'LA Galaxy', 'Al Nassr', 'SC Freiburg',
       'SC Braga', 'Olympiacos CFP', 'Toronto FC', 'Granada CF',
       'FC Schalke 04', 'RC Strasbourg Alsace', 'Hertha BSC',
       'AZ Alkmaar', 'Seattle Sounders FC', 'Montpellier HSC',
       'Shanghai Greenland Shenhua FC', 'Hamburger SV', 'Girona FC',
       'Racing Club', 'Portland Timbers', 'FC Girondins de Bordeaux',
       'Watford', 'Estudiantes de La Plata', 'Club América',
       'Vitória Guimarães', 'SK Slavia Praha', 'Trabzonspor',
       'RCD Espanyol', 'FC Nantes', 'Angers SCO', 'Cruz Azul',
       'BSC Young Boys', 'Club León', 'Spartak Moscow', 'Sivasspor',
       'Elche CF', 'FC Augsburg', 'Wuhan Zall', 'Parma',
       'Royal Antwerp FC', 'Monterrey', 'San Lorenzo de Almagro',
       'AC Monza', 'Club Atlético Lanús', 'SD Huesca', 'Derby County',
       'Kayserispor', 'RSC Anderlecht', 'CD Leganés', 'Vélez Sarsfield',
       'Stade Brestois 29', 'Tianjin TEDA FC', 'Birmingham City',
       'Hellas Verona', '1. FC Köln', 'Al Wehda', 'Bournemouth',
       'Alanyaspor', 'Bologna', 'Amiens SC', 'Celtic',
       'Shijiazhuang Ever Bright F.C.', 'Club Atlas', 'Al Ahli',
       'Norwich City', 'Fatih Karagümrük S.K.', 'Club Tijuana',
       'Universidad Católica', 'Goiás', 'Benevento', 'Independiente',
       'Qingdao Huanghai F.C.', 'Brentford', 'AEK Athens',
       'Racing Club de Lens', 'Olimpia Asunción', 'Shenzhen FC',
       'Çaykur Rizespor', 'KAA Gent', 'New England Revolution',
       'Cádiz CF', '1. FSV Mainz 05', 'Vasco da Gama', 'FC Midtjylland',
       'Al Ain FC', 'Santos Laguna', 'SPAL', 'Perth Glory', 'FC Utrecht',
       'Montreal Impact', 'UD Almería', 'Fortaleza', 'Spezia',
       'FC Basel 1893', 'FC København', 'Godoy Cruz', 'Deportivo Toluca',
       'Nacional de Montevideo', 'Aalborg BK', 'Rio Ave FC', 'FC Metz',
       'Chongqing Dangdai Lifan FC SWM Team', 'Rosenborg BK',
       'FC Red Bull Salzburg', 'Botafogo', 'DSC Arminia Bielefeld',
       'Club Athletico Paranaense', 'RCD Mallorca', 'Pachuca',
       'Swansea City', 'KRC Genk', 'En Avant de Guingamp', 'Lecce',
       'Nîmes Olympique', 'Colo-Colo', 'Stade Malherbe Caen',
       'Columbus Crew SC', 'Junior FC', 'VfB Stuttgart', 'Moreirense FC',
       'Rangers FC', 'Malmö FF', 'Shandong Luneng TaiShan FC',
       'Sparta Praha', 'Hatayspor', 'Chicago Fire',
       'Toulouse Football Club', 'FC Seoul', 'Antalyaspor',
       'Deportivo Cali', 'Kaizer Chiefs', 'Real Zaragoza',
       'Atlético Clube Goianiense', 'Puebla FC', 'Fortuna Düsseldorf',
       'Western United FC', 'Astra Giurgiu', 'Henan Jianye FC', 'Bahia',
       'Famalicão', 'Atiker Konyaspor', 'Peñarol', 'DC United',
       'New York City FC', 'Argentinos Juniors', 'U.N.A.M.',
       'Minnesota United FC', 'Nottingham Forest',
       'Independiente del Valle', 'Defensa y Justicia',
       'Philadelphia Union', "Newell's Old Boys", 'Rosario Central',
       'Atlético de San Luis', 'FC Dallas', 'Denizlispor',
       'Yeni Malatyaspor', 'Club Atlético Colón', 'Houston Dynamo',
       'Millwall', 'Clube Sport Marítimo', 'MKE Ankaragücü',
       'Guadalajara', 'Boavista FC', 'Sporting Kansas City',
       'Atlético Nacional', 'CD Lugo', 'New York Red Bulls', 'PAOK',
       'SC Heerenveen', 'Daegu FC', 'Preston North End', 'Damac FC',
       'Brescia', 'VfL Bochum 1848', 'Vancouver Whitecaps FC',
       'SV Sandhausen', 'Royal Excel Mouscron', 'Dijon FCO', 'Molde FK',
       'Panathinaikos FC', 'LASK Linz', 'Ulsan Hyundai FC',
       'Real Salt Lake', 'FC Luzern', 'Viktoria Plzeň', 'Orlando Pirates',
       'Al Ittihad', '1. FC Nürnberg', 'Standard de Liège',
       'Rayo Vallecano', 'Club Libertad', 'Jeonbuk Hyundai Motors',
       'Western Sydney Wanderers', 'Unión de Santa Fe', 'FC Sion',
       'Sydney FC', 'Hannover 96', 'Real Sporting de Gijón',
       'FC Cincinnati', 'ESTAC Troyes', 'San Jose Earthquakes',
       'Club Guaraní', 'FC Lorient', 'Gençlerbirliği SK',
       'Sporting de Charleroi', 'Wisła Kraków', 'Al Taawoun', 'Reading',
       'Gazişehir Gaziantep F.K.', 'Blackburn Rovers', 'Kashiwa Reysol',
       'FK Bodø/Glimt', 'Willem II', 'Vitesse', 'Gil Vicente FC',
       'SønderjyskE', 'Yokohama F. Marinos', 'FC St. Gallen',
       'Club Atlético Aldosivi', 'Göztepe SK', 'Holstein Kiel',
       'FC Juárez', 'FCSB (Steaua)', 'Ettifaq FC', 'KAS Eupen',
       'FC Tokyo', 'Melbourne City FC', 'Universitatea Craiova',
       'CD Tondela', 'Wolfsberger AC', 'Ceará Sporting Club',
       'River Plate Asunción', 'Stoke City', 'Paris FC', 'IFK Norrköping',
       'Crotone', 'Cardiff City', 'América de Cali', 'Al Faisaly',
       'Independiente Medellín', 'Portimonense SC', 'CD Tenerife',
       'Heracles Almelo', 'Nashville SC', 'SK Rapid Wien',
       'Kawasaki Frontale', 'Club Necaxa', 'Chievo Verona', 'Lech Poznań',
       'AIK', 'FK Austria Wien', 'Querétaro', '1. FC Heidenheim 1846',
       'Legia Warszawa', 'Club Atlético Banfield', 'Os Belenenses',
       'Huddersfield Town', 'KSV Cercle Brugge', 'LDU Quito',
       'Gimnasia y Esgrima La Plata', 'Gamba Osaka', 'Middlesbrough',
       'Servette FC', 'Empoli', 'Real Oviedo', 'Kasimpaşa SK', 'CFR Cluj',
       'Millonarios FC', 'FC Paços de Ferreira', 'Sint-Truidense VV',
       'AD Alcorcón', 'Colorado Rapids', 'Dinamo Bucureşti',
       'Cerezo Osaka', 'FC Emmen', 'Sheffield Wednesday',
       'FC Erzgebirge Aue', 'Raków Częstochowa', 'Atlético Tucumán',
       'SV Darmstadt 98', 'Bristol City', 'Oud-Heverlee Leuven',
       'Barnsley', 'Queens Park Rangers', 'Sangju Sangmu FC',
       'Helsingborgs IF', 'AC Ajaccio', 'Oceânico FC',
       'Club Atlético Talleres', 'Al Hazem', 'SC Paderborn 07',
       'Club Atlético Huracán', 'KV Kortrijk', 'El Nacional',
       'Mazatlán FC', 'Aberdeen', 'CD Mirandés', 'SV Zulte-Waregem',
       'Piast Gliwice', 'Djurgårdens IF', 'Central Córdoba',
       'Wellington Phoenix', 'Deportivo Binacional', 'Patronato',
       'SpVgg Greuther Fürth', 'IFK Göteborg', 'FC Cartagena',
       'Santa Clara', 'FC Twente', 'Farense', 'ADO Den Haag',
       'AJ Auxerre', 'Al Fateh', 'Valenciennes FC',
       'Hokkaido Consadole Sapporo', 'FC St. Pauli', 'Albacete BP',
       '1. FC Kaiserslautern', 'Al Fayha', 'Incheon United FC',
       'KV Mechelen', 'Pohang Steelers', 'CD Nacional', 'Unión La Calera',
       'BB Erzurumspor', 'Kashima Antlers', 'Arsenal de Sarandí',
       'HJK Helsinki', 'Karlsruher SC', 'Aarhus GF', 'FC Zürich',
       'Barcelona Sporting Club', 'SG Dynamo Dresden',
       'Sanfrecce Hiroshima', 'Al Raed', 'SD Ponferradina', 'Brøndby IF',
       'Lechia Gdańsk', 'FC Viitorul', 'SK Sturm Graz', 'IF Elfsborg',
       'Gangwon FC', 'Melgar FBC', 'Club Atlético Grau',
       'Jagiellonia Białystok', 'Waasland-Beveren', 'VfL Osnabrück',
       'Nagoya Grampus', 'CF Fuenlabrada', 'Shamrock Rovers',
       'Shimizu S-Pulse', 'RKC Waalwijk', 'Vålerenga Fotball',
       'Clermont Foot 63', 'FC Ingolstadt 04', 'FC Würzburger Kickers',
       'Górnik Zabrze', 'Charlton Athletic', 'Beerschot AC',
       'Coquimbo Unido', 'Viktoria Köln', 'Hull City', 'Málaga CF',
       'FC Nordsjælland', 'UD Las Palmas', 'VVV-Venlo', 'GwangJu FC',
       'Chamois Niortais Football Club', 'FC Lugano', 'Cusco FC',
       'Sparta Rotterdam', 'Sol de América', 'PEC Zwolle',
       'Pogoń Szczecin', 'Doncaster Rovers', 'Kristiansund BK',
       'Liverpool Fútbol Club', 'Club Bolívar', 'Urawa Red Diamonds',
       'SK Brann', 'Eintracht Braunschweig', 'Nacional Asunción',
       'Melbourne Victory', 'Kilmarnock', 'Dundalk',
       'SSV Jahn Regensburg', 'Abha Club', 'Club Atlético Tigre',
       'Suwon Samsung Bluewings', 'Shonan Bellmare', 'SD Aucas', 'Emelec',
       'Fortuna Sittard', 'La Berrichonne de Châteauroux',
       'Śląsk Wrocław', 'Coventry City', 'Sunderland', 'Alianza Lima',
       'Hammarby IF', 'Cracovia', 'CE Sabadell FC', 'Oita Trinita',
       'BK Häcken', 'Luton Town', 'Le Havre AC', 'IK Sirius',
       'Zagłębie Lubin', 'Grenoble Foot 38', 'Macarthur FC',
       'Rodez Aveyron Football', 'Vegalta Sendai', 'Motherwell',
       'SV Wehen Wiesbaden', 'Audax Italiano', 'Gaz Metan Mediaş',
       'Portsmouth', 'Hibernian', 'Always Ready', 'UD Logroñés',
       'FC Voluntari', 'FC Hermannstadt', 'AS Nancy Lorraine',
       'Rotherham United', 'Fleetwood Town', 'Jorge Wilstermann',
       'Odense Boldklub', 'MSV Duisburg', 'FC Sochaux-Montbéliard',
       'Milton Keynes Dons', 'River Plate Montevideo', 'Delfín SC',
       'Universidad Católica del Ecuador', 'Deportivo Pasto',
       'KV Oostende', 'Club Plaza Colonia', 'Wigan Athletic',
       'FC Botoşani', 'C.D. Castellón', 'SCR Altach', 'Örebro SK',
       'TSV Hartberg', 'Stabæk Fotball', 'Wycombe Wanderers',
       'St. Johnstone FC', 'Oxford United', 'Lincoln City', 'Randers FC',
       'Viking FK', 'FC Chambly Oise', 'Dundee United',
       'Oriente Petrolero', 'Odds BK', 'Nacional Potosí', 'Sepsi OSK',
       'FC Hansa Rostock', 'Lyngby BK', 'SpVgg Unterhaching',
       'Brisbane Roar', 'Seongnam FC', 'SV Ried', 'CD Huachipato',
       'WSG Tirol', 'Podbeskidzie Bielsko-Biała', 'Peterborough United',
       'Club Blooming', 'Wisła Płock', 'Busan IPark', 'FSV Zwickau',
       'Mjøndalen IF', 'Vejle Boldklub', 'Pau FC', 'FC Lausanne-Sport',
       'Estudiantes de Mérida', 'Sagan Tosu', 'SV Waldhof Mannheim',
       'Sport Huancayo', 'Hallescher FC', 'Kalmar FF', 'St. Mirren',
       'SKN St. Pölten', 'Sarpsborg 08 FF', 'Shrewsbury',
       'TSV 1860 München', 'SV Meppen', 'Ipswich Town', 'IK Start',
       'Adelaide United', 'Stal Mielec', 'Centro Atlético Fénix',
       'Newcastle Jets', 'Livingston FC', 'AC Mineros de Guayana',
       'AFC Wimbledon', 'Burton Albion', 'Al Adalah', 'Warta Poznań',
       'USL Dunkerque', 'Bristol Rovers', 'UTA Arad', 'Östersunds FK',
       'Sportivo Luqueño', 'Politehnica Iaşi', 'Salford City',
       'Central Coast Mariners', 'Caracas FC', 'AC Horsens',
       'Plymouth Argyle', 'Aalesunds FK', 'Crewe Alexandra',
       'Chindia Târgovişte', 'Oldham Athletic', 'Yokohama FC',
       'Blackpool', 'Northampton Town', 'Bayern München II',
       'FK Haugesund', 'KFC Uerdingen 05', 'Forest Green Rovers',
       'Cheltenham Town', 'Strømsgodset IF', 'Mjällby AIF', 'Exeter City',
       'Cambridge United', 'Grimsby Town', 'FC Vaduz', 'Türkgücü München',
       'VfB Lübeck', 'Bolton Wanderers', 'Bradford City',
       '1. FC Magdeburg', 'FC Admira Wacker Mödling',
       'Hamilton Academical FC', 'Aragua FC', 'Accrington Stanley',
       'Swindon Town', 'Carlisle United', 'FC Argeș', 'Port Vale',
       'Academica Clinceni', 'Rochdale', 'Gillingham', 'Tranmere Rovers',
       'Southend United', '1. FC Saarbrücken', 'Colchester United',
       'Mansfield Town', 'Falkenbergs FF', 'SC Verl', 'Varbergs BoIS',
       'Crawley Town', 'Sandefjord Fotball', 'Newport County',
       'Bohemian FC', 'Ross County FC', 'Scunthorpe United', 'Morecambe',
       'Walsall', 'Leyton Orient', 'Stevenage', 'Barrow', 'Derry City',
       'Llaneros de Guanare', 'Sligo Rovers', 'Zamora FC',
       "St. Patrick's Athletic", 'Cork City', 'Shelbourne FC',
       'Harrogate Town', 'Waterford FC', 'Finn Harps'], dtype=object)

In [18]:
#cleaning contract column
raw['Contract'].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 2028',
       '2010 ~ 2023', '2014 ~ 2021', '2015 ~ 2025', '2014 ~ 2026',
       '2012 ~ 2025', '2017 ~ 2020', '2002 ~ 2022', '2020 ~ 2027',
       '2013 ~ 2025', 'Dec 31, 2020 On Loan', '2019 ~ 2020',
       '2011 ~ 2025', '2016 ~ 2020', '2007 ~ 2021', '2020 ~ 2026',
       '2010 ~ 2025', '2009 ~ 2023', '2008 ~ 2021', '2020 ~ 2020',
       '2016 ~ 2026', 'Jan 30, 2021 On Loan', '2012 ~ 2020',
       '2014 ~ 2025', 'Jun 30, 2022 On Loan', '2015 ~ 2020',
       'May 31, 2021 On Loan', '2018 ~ 2020', '2014 ~ 2020',
       '2013 ~ 2020', '2006 ~ 2024', 'Jul 5, 2021 On Loan',
       'Dec 31, 2021 On Loan', '2004 ~ 2025', '2011 ~ 2020',
       'Jul 1, 2021 On Loan', 'Jan 1, 2021 On Loan', '2006 ~ 2023',
       'Aug 31, 2021 On Loan', '2006 ~ 2021', '2005 ~ 2023',
       '2003 ~ 2020', '2009 ~ 2020', '2002 ~ 2020', '2005 ~ 2020',
       '2005 ~ 2022', 'Jan 31, 2021 On Loan', '2010 ~ 2020',
       'Dec 30, 2021 On Loan', '2008 ~ 2020', '2007 ~ 2020',
       '2003 ~ 2021', 'Jun 23, 2021 On Loan', 'Jan 3, 2021 On Loan',
       'Nov 27, 2021 On Loan', '2002 ~ 2021', 'Jan 17, 2021 On Loan',
       'Jun 30, 2023 On Loan', '1998 ~ 2021', '2003 ~ 2022',
       '2007 ~ 2023', 'Jul 31, 2021 On Loan', 'Nov 22, 2020 On Loan',
       'May 31, 2022 On Loan', '2006 ~ 2020', 'Dec 30, 2020 On Loan',
       '2007 ~ 2025', 'Jan 4, 2021 On Loan', 'Nov 30, 2020 On Loan',
       '2004 ~ 2020', '2009 ~ 2025', 'Aug 1, 2021 On Loan'], dtype=object)

In [19]:
# define a function to extract player status
def get_player_status(duration):
    if 'On Loan' in duration:
        return 'On loan'
    elif 'Free' in duration:
        return 'Free'
    else:
        return 'Long term'

# apply the function to create the "player_status" column
raw['Player_status'] = raw['Contract'].apply(get_player_status)

In [20]:
raw['Player_status'].unique()

array(['Long term', 'On loan', 'Free'], dtype=object)

In [21]:
 #extract contract start and end dates
# define regular expressions to extract year values
start_regex = r'(\d{4})'
end_regex = r'(On Loan|\d{4})'

# extract year values and assign to new columns
raw['Contract_start'] = raw['Contract'].str.extract(start_regex)
raw['Contract_end'] = raw['Contract'].str.extract(end_regex)

# replace "On Loan" with contract start year
raw['Contract_end'] = raw['Contract_end'].apply(lambda x: raw['Contract_start'] if x == 'On Loan' else x)

# convert columns to datetime
raw['Contract_start'] = pd.to_datetime(raw['Contract_start'], format='%Y')
raw['Contract_end'] = pd.to_datetime(raw['Contract_end'], format='%Y')
#Years only
raw['Contract_end']=raw['Contract_end'].dt.strftime('%Y')
raw['Contract_Start']=raw['Contract_start'].dt.strftime('%Y')

In [22]:
raw[['Contract_end','Contract_Start', 'Player_status']]

      Contract_end Contract_Start Player_status
0             2004           2004     Long term
1             2018           2018     Long term
2             2014           2014     Long term
3             2015           2015     Long term
4             2017           2017     Long term
...            ...            ...           ...
18974         2018           2018     Long term
18975         2020           2020     Long term
18976         2019           2019     Long term
18977         2020           2020     Long term
18978         2019           2019     Long term

[18979 rows x 3 columns]

In [23]:
#cleaning Positions column
po=set(''.join(raw['Positions'].tolist()))
raw[raw['Positions'].str.contains('[^a-zA-Z\s]', regex=True)]['Positions'].to_list()

['RW, ST, CF',
 'ST, LW',
 'CAM, CM',
 'LW, CAM',
 'ST, LW, RW',
 'CF, ST',
 'LW, RW',
 'CDM, CM',
 'CDM, RB',
 'CF, CAM',
 'LW, ST',
 'ST, CF, LW',
 'RM, LM, CAM',
 'RW, CAM, CM',
 'CAM, CM',
 'LM, CF',
 'CDM, CM',
 'ST, LW',
 'RW, LW',
 'CAM, RM, RW',
 'CM, CDM',
 'CM, CDM',
 'CAM, CM',
 'CAM, CF, ST',
 'CDM, CM',
 'CDM, CM',
 'CM, CDM, CAM',
 'CF, LW, CAM',
 'CAM, RM, CF',
 'LM, ST',
 'RM, LM, RW',
 'CAM, RW',
 'CB, CDM',
 'RW, RM',
 'ST, LW',
 'LW, CF',
 'CM, RM, LM',
 'LB, LM',
 'CM, CDM',
 'CAM, CM, RM',
 'CF, ST',
 'CAM, CM, CF',
 'CAM, CF',
 'CDM, CM',
 'CAM, CM',
 'LW, RW',
 'LM, RM, LW',
 'LM, LB, CM',
 'CM, CDM',
 'CM, LM, LB',
 'CDM, CM',
 'CF, ST',
 'RM, RW',
 'RM, CM',
 'CAM, CM, LW',
 'CB, LB',
 'CDM, CM',
 'RM, RB',
 'ST, RW',
 'LM, RW, LW',
 'CB, CDM',
 'RB, LB',
 'CDM, CM',
 'RB, RM',
 'LW, RW',
 'LM, RM, CF',
 'CAM, RM',
 'RB, RWB',
 'CDM, CB, CM',
 'CAM, RM, ST',
 'LB, LM',
 'LM, LW, RM',
 'CAM, CM',
 'CM, CAM',
 'ST, RM, CF',
 'LM, RM',
 'RM, CF',
 'LM, LWB',
 'CAM, CM',
 'LB, LM',
 'CM, CDM',
 'RW, RM, CF',
 'CM, CAM',
 'CM, CDM',
 'CDM, CM',
 'CF, LW, CAM',
 'CDM, CM',
 'RB, CM',
 'CDM, CM',
 'LM, CF',
 'LW, CAM, RW',
 'CAM, LW, CM',
 'CAM, CM, LW',
 'CM, CDM',
 'CM, CAM, CDM',
 'CM, CDM',
 'CM, CDM, CAM',
 'CAM, CM, CF',
 'CM, CDM',
 'CB, LB',
 'RW, LW, CAM',
 'CM, CAM, LM',
 'CB, LB',
 'RW, RM',
 'CM, CAM',
 'CM, RM, ST',
 'RM, RW',
 'CDM, CM, RB',
 'LW, RW',
 'LB, LM',
 'ST, CAM',
 'CAM, LW, ST',
 'RW, LW',
 'CM, CDM',
 'LB, CB, LWB',
 'CAM, RW',
 'RM, ST',
 'CB, CDM, LB',
 'ST, CAM',
 'RWB, RM',
 'CAM, RW',
 'CDM, CM',
 'CM, LM, RM',
 'RM, RW',
 'RB, CDM, CM',
 'CM, CAM',
 'CAM, RW',
 'LW, CAM',
 'RW, LW, RM',
 'LM, LW',
 'CM, LM',
 'LM, LB',
 'LM, LW',
 'RM, LM, CF',
 'CF, ST',
 'RM, RW',
 'LB, LM, RM',
 'CDM, CM, CAM',
 'ST, LW, RM',
 'CAM, CM, ST',
 'LB, LM',
 'ST, CF',
 'LWB, LB',
 'CB, CDM',
 'LW, RW, LM',
 'CDM, CM',
 'RM, RW, ST',
 'CAM, CM, LW',
 'CDM, CM',
 'ST, RW',
 'CM, CAM',
 'CF, ST, CAM',
 'LM, CAM, RM',
 'CM, CDM',
 'CDM, CM',
 'LM, ST',
 'CDM, CM',
 'RB, CB',
 'CDM, CM',
 'CM, CDM, CAM',
 'ST, LM',
 'RW, CAM',
 'LM, CAM',
 'RWB, RB',
 'ST, RW, LW',
 'RW, CAM',
 'RB, RM',
 'CB, CDM',
 'RB, RM, RW',
 'CM, CAM',
 'LB, LWB',
 'CAM, CM',
 'RM, RW',
 'RM, CAM',
 'CAM, ST',
 'CM, CDM',
 'CDM, CB',
 'LM, CAM',
 'CM, CDM, CAM',
 'CF, LM, LW',
 'ST, CF',
 'CB, CDM',
 'LB, LM',
 'CDM, CM',
 'CAM, LM, LW',
 'ST, CF',
 'CAM, RM',
 'CM, CDM',
 'LB, LWB',
 'LW, RW, CAM',
 'CAM, ST',
 'CB, RB',
 'CAM, CM, LW',
 'CDM, CM',
 'LW, ST',
 'CAM, LM, LW',
 'RB, RM',
 'LM, RM',
 'RB, CB, RWB',
 'CM, CAM',
 'LM, LW, ST',
 'LW, ST, CM',
 'CM, CAM',
 'CM, CDM',
 'RM, CAM, CM',
 'CB, RB, RWB',
 'RW, ST, LW',
 'CM, CDM',
 'CM, LM',
 'ST, LW',
 'RM, RW',
 'LW, CAM, CM',
 'CDM, CM',
 'RW, RM',
 'RM, RW',
 'RB, LB',
 'CAM, RM',
 'CM, CAM, LM',
 'CAM, CM, LW',
 'CDM, CM',
 'CM, LM, CDM',
 'LB, LM, LWB',
 'CB, LB, RB',
 'LM, CF',
 'CAM, LW',
 'LB, LM',
 'RWB, RB, RM',
 'RB, RWB',
 'CDM, CM',
 'CDM, CM',
 'CF, CAM, ST',
 'RM, CAM, RW',
 'LB, LM',
 'CB, CDM',
 'CDM, CM',
 'CDM, CM',
 'RB, RWB',
 'RW, ST',
 'CDM, CM',
 'CAM, CF',
 'CB, RB',
 'CDM, CB',
 'CAM, ST',
 'CM, CDM',
 'CB, RB',
 'LW, LM',
 'RB, RM, CM',
 'RM, CAM',
 'ST, CAM, RW',
 'RM, CAM',
 'CM, CAM, CDM',
 'RW, LW',
 'LW, RW',
 'CM, RB, LB',
 'LM, RM',
 'CDM, CM, CAM',
 'RB, RM',
 'LB, LM',
 'CM, CAM',
 'CAM, LM, RM',
 'RW, LW',
 'LB, LM',
 'RB, RW',
 'CDM, CM',
 'LB, LWB',
 'CAM, CM',
 'LM, CM',
 'CDM, CM',
 'CDM, CM',
 'LW, CAM',
 'RM, CAM',
 'CDM, CB',
 'CDM, CM',
 'RM, LM, CM',
 'CDM, CM, CB',
 'CM, CF',
 'CDM, CM',
 'LB, LM',
 'CF, LW, RW',
 'ST, RM',
 'CAM, CM, CDM',
 'ST, RM',
 'LM, CAM, RM',
 'CM, CAM',
 'RB, RWB',
 'CM, CDM, CAM',
 'LW, RW, LM',
 'CDM, CM',
 'LB, CB',
 'CDM, CM',
 'ST, RW, LW',
 'ST, CAM',
 'CDM, CM, CB',
 'CDM, CM',
 'CDM, CM',
 'RW, RWB',
 'ST, LM, RM',
 'CM, CDM',
 'RW, RM',
 'LB, LWB',
 'CDM, CM',
 'CAM, ST',
 'LW, RW',
 'LB, LM',
 'CM, CDM',
 'RM, RWB, RB',
 'LM, ST, CAM',
 'CAM, ST, CF',
 'CDM, CM',
 'CDM, CM',
 'CAM, CM',
 'LW, CM',
 'CM, CDM',
 'CDM, CM',
 'CDM, CM',
 'RB, RWB, LB',
 'CM, CDM',
 'RM, LM',
 'RM, LM',
 'RW, LW',
 'CM, CAM, RM',
 'CDM, CM',
 'RB, LB',
 'CF, CAM',
 'CM, CDM',
 'CDM, CM',
 'RM, LM, CAM',
 'CM, CDM',
 'LW, LM',
 'CDM, CM',
 'ST, LW, CAM',
 'CDM, CM',
 'RM, RW, CAM',
 'CAM, CM',
 'LM, LW',
 'CDM, CM',
 'CM, CDM, RM',
 'RM, LM',
 'CDM, CM',
 'LB, LWB',
 'CAM, RM',
 'LM, CAM',
 'CDM, CM',
 'CAM, ST',
 'CDM, CM, CB',
 'RM, LM',
 'RB, LB',
 'RW, LW',
 'RW, LW, CAM',
 'CB, LB',
 'CM, CDM',
 'RB, RM, CM',
 'RB, RM, RWB',
 'CDM, CB, LB',
 'CDM, CB',
 'CAM, ST, LM',
 'RM, CAM',
 'LM, CM, RM',
 'CM, CDM',
 'RW, CAM',
 'CF, RW',
 'RM, RW',
 'ST, RW',
 'RB, RWB',
 'CAM, RM, LW',
 'CM, RM, CDM',
 'RM, ST',
 'CM, CAM',
 'RM, RW',
 'LW, LM',
 'RB, RM, CM',
 'CB, LB',
 'RB, LB',
 'LB, LWB, LM',
 'ST, CAM',
 'CDM, CM',
 'CM, CDM',
 'LW, RW, CF',
 'LB, LWB',
 'CB, LB',
 'ST, LW',
 'RB, RWB',
 'ST, LM',
 'CDM, CM',
 'ST, LM, RM',
 'RM, RW, CAM',
 'LW, LM, CAM',
 'LWB, LW, LB',
 'CM, CDM',
 'RB, CB',
 'RB, RWB',
 'CDM, CM',
 'CDM, CM',
 'CM, LM',
 'CM, CDM',
 'CDM, CM, LM',
 'CB, CM',
 'RWB, RW, RB',
 'LB, LWB',
 'CDM, CM',
 'LM, CF',
 'RB, LB',
 'LM, ST',
 'CM, CDM, CAM',
 'LB, LWB',
 'RB, LB',
 'CB, CM',
 'CDM, CM, CAM',
 'CDM, CM',
 'LW, ST',
 'LM, LW',
 'CM, CDM',
 'RB, LB',
 'ST, RW, RM',
 'CM, CDM',
 'LM, CAM',
 'LW, RW, CM',
 'LM, RM, CAM',
 'LB, RB',
 'CAM, CM',
 'CAM, CM',
 'LM, RM',
 'RWB, RM, RB',
 'CDM, CB',
 'CDM, CM',
 'RW, RM',
 'CB, RB',
 'CM, CAM',
 'RB, RM',
 'CM, CDM',
 'RB, RW',
 'LM, RB, LB',
 'LB, LM, LWB',
 'LW, RW',
 'CDM, CM',
 'LW, LM, ST',
 'LM, LB',
 'ST, RM, LM',
 'LWB, LB',
 'ST, RW',
 'CAM, CM, LM',
 'CF, CM',
 'LW, ST, RW',
 'ST, LW',
 'CDM, CM',
 'CDM, CM, CB',
 'CDM, CM',
 'CDM, CM',
 'CF, ST',
 'LM, LW, RM',
 'RB, CB, RWB',
 'ST, CAM, CF',
 'LB, CB, LM',
 'CM, CDM',
 'CM, CDM, LM',
 'RM, RWB',
 'RM, LM',
 'LB, LM, RB',
 'CDM, CM',
 'RM, CM',
 'CM, CAM',
 'RM, CM',
 'CB, RB',
 'LB, LM',
 'CAM, CM',
 'RW, LW',
 'CM, CDM, CAM',
 'ST, CF',
 'LM, CAM',
 'CAM, CF',
 'CM, CDM, CAM',
 'CB, CDM',
 'RB, LB, CB',
 'CM, CDM',
 'CDM, CM',
 'CM, CDM, RB',
 'LB, LWB',
 'LB, LM',
 'RW, LW',
 'RW, ST',
 'ST, CAM',
 'RM, LM',
 'LB, CM',
 'ST, RM',
 'LM, ST',
 'ST, CAM',
 'CM, CAM, CDM',
 'CM, CDM',
 'CF, CAM, LW',
 'CM, CAM',
 'CDM, CM',
 'ST, LW',
 'CDM, CM',
 'RM, LWB',
 'CB, RB',
 'CF, ST, LM',
 'LB, RB, CB',
 'RB, CM',
 'CDM, CM',
 'LM, LW',
 'CDM, CB',
 'CAM, CM',
 'RB, RWB',
 'RM, LM, CM',
 'CM, CAM, LM',
 'RB, RM',
 'LW, CF, ST',
 'CDM, CM',
 'RW, CAM',
 'CDM, CM',
 'RWB, RB',
 'RM, LM',
 'CM, CDM',
 'CM, CDM',
 'LM, CAM',
 'LB, LM',
 'LM, CF',
 'CM, CDM',
 'RM, ST',
 'RM, ST, CAM',
 'RM, ST',
 'LW, RW, ST',
 'RWB, RM',
 'ST, LW, LM',
 'CM, LW',
 'CDM, CM, LB',
 'CM, CF',
 'CAM, RM',
 'CB, RB',
 'LM, RM, CAM',
 'CM, RM, CAM',
 'RB, RM',
 'CM, CDM',
 'CM, CDM',
 'ST, CF, CAM',
 'LB, LWB',
 'CDM, CM',
 'CM, LM, CAM',
 'CM, CDM',
 'CM, CAM',
 'LM, ST, RM',
 'LB, LWB, LM',
 'CAM, RM, CM',
 'RB, RM, RWB',
 'CDM, CM',
 'LW, LM',
 'CAM, LM, CM',
 'LM, RM',
 'ST, CAM',
 'CAM, CM',
 'RW, LW, ST',
 'CAM, CM',
 'CDM, CM',
 'RM, ST',
 'RM, LM, CF',
 'CAM, RM, LM',
 'CF, ST, LW',
 'LWB, LB, LM',
 'CAM, RM, CM',
 'LM, LW',
 'LB, CB',
 'RM, CM, CAM',
 'CB, RB',
 'CM, CDM',
 'RB, RW',
 'CDM, CM',
 'RM, RW',
 'LB, LM, CAM',
 'CDM, CM',
 'CM, CDM',
 'CAM, CDM',
 'CDM, CM',
 'CM, CDM',
 'CDM, CM',
 'CDM, CM',
 'RW, RB, RM',
 'CM, CAM',
 'RB, RM',
 'LW, RW',
 'CDM, CM',
 'RM, ST, RW',
 'CDM, CM',
 'CM, CAM, LW',
 'RM, CM',
 'CF, ST, RW',
 'CB, CDM',
 'CAM, CF',
 'CM, CDM, RM',
 'ST, CAM',
 'CB, LB',
 'RB, RM',
 'RM, RW',
 'LM, RM, RB',
 'CDM, CM',
 'LM, RM, CM',
 'CDM, CB',
 'CB, CDM',
 'CDM, CM',
 'CB, RB, RM',
 'RB, CDM',
 'RM, ST, LM',
 'LB, LWB, CB',
 'RM, LM',
 'CDM, LB',
 'RM, LM, RW',
 'CDM, CM',
 'RM, RWB, RB',
 'CAM, CM',
 'CDM, CB',
 'LB, LWB',
 'RB, RWB',
 'LB, LWB',
 'CDM, CB',
 'ST, CF, CAM',
 'ST, RW',
 'ST, LW',
 'LM, LW',
 'CM, CDM',
 'ST, CAM',
 'CDM, CM',
 'LM, RM, ST',
 'RB, RWB',
 'CDM, CM',
 'LB, LM',
 'CAM, LM, CM',
 'CM, CDM, CAM',
 'CDM, CM',
 'CAM, CF, ST',
 'ST, CAM',
 'RWB, RB, LWB',
 'CAM, RW',
 'CDM, CM',
 'LB, LM',
 'CAM, CF',
 'CAM, CF',
 'RM, RW',
 'CDM, CM',
 'ST, LM, CAM',
 'RM, ST, LM',
 'RB, LB',
 'LM, RM',
 'LW, RW, CF',
 'LW, CAM',
 'ST, LM',
 'RB, RM',
 'CDM, CM',
 'LB, LM',
 'LM, RM',
 'RM, RW',
 'CDM, CM',
 'ST, RM, CAM',
 'RM, LM',
 'RB, RWB, RM',
 'CDM, CM',
 'CF, LM, CAM',
 'RW, RM',
 'RB, LB',
 'CAM, RM',
 'CM, CDM',
 'CB, CDM',
 'ST, CF',
 'CM, LM, RM',
 'CM, CDM, CAM',
 'CDM, CM',
 'CDM, CM',
 'ST, CF, CAM',
 'RM, LM',
 'LB, CB',
 'CDM, CM',
 'CDM, CM',
 'ST, CAM',
 'CM, CDM, RM',
 'CAM, RM, LM',
 'CAM, CF, RW',
 'CM, CDM',
 'CM, CAM',
 'CM, CDM',
 'RB, RM, LB',
 'CB, CDM',
 'LM, LW',
 'LW, ST',
 'ST, RW',
 'CDM, CM',
 'CAM, CF, ST',
 'CAM, LW, ST',
 'CAM, CM',
 'CM, CDM',
 'CDM, CM',
 'LW, LM',
 'CDM, RWB',
 'ST, RW, LW',
 'CDM, CM',
 'CM, CAM, CDM',
 'CDM, CM',
 'CDM, CM',
 'CAM, RM',
 'CM, RW, CAM',
 'CM, CDM',
 'RB, RWB',
 'CM, CAM, RM',
 'RB, RWB',
 'CM, CAM, CDM',
 'RM, CAM, CM',
 'LW, ST',
 'LM, RM, CAM',
 'CAM, RM',
 'CB, CDM',
 'RM, LM',
 'CB, CDM',
 'RW, ST, LW',
 'CB, RB',
 'RM, RB',
 'RB, RWB',
 'LM, RM',
 'CF, ST',
 'ST, CF, LM',
 'CM, RM, CDM',
 'RM, LM, RWB',
 'RM, ST, LM',
 'CDM, CB',
 'LM, CM',
 'CDM, CM',
 'CDM, CM',
 'LM, LB',
 'CDM, CM',
 'RM, ST, CAM',
 'RM, LM',
 'CM, CDM, RM',
 'ST, RW',
 'RM, CAM',
 'CAM, LM, CM',
 'LB, LWB, LM',
 'CM, CAM',
 'CDM, CM',
 'CB, CDM',
 'CDM, CM',
 'CAM, RM',
 'RB, LB, RM',
 'CM, CDM',
 'RB, RWB',
 'CDM, CM',
 'CM, CDM',
 'CB, RB',
 'RM, LM',
 'RB, RM',
 'CAM, RM',
 'CM, CAM',
 'LM, RM',
 'CDM, CM',
 'LB, LM',
 'CM, RM, CAM',
 'CM, CAM',
 'CDM, CM',
 'RB, LB',
 'LB, LWB',
 'LW, RW',
 'CAM, CM',
 'LM, LW, ST',
 'RM, LM',
 'CM, CDM',
 'CM, RM, CDM',
 'RWB, RB, RM',
 'CB, CDM',
 'LM, LW, LB',
 'RM, LM, ST',
 'RB, RWB',
 'CB, CDM',
 'CDM, CM',
 'RM, ST, RW',
 'CDM, CM',
 'CAM, LM',
 'LB, LM',
 'LM, CF',
 'CB, CDM',
 'CM, CDM, CAM',
 'ST, LM, LW',
 'ST, RW',
 'CDM, CM',
 'RB, RM',
 'LW, RW',
 'LB, LWB',
 'LM, ST, RM',
 'CDM, CM',
 'CDM, CM',
 'CDM, CM',
 'CM, CDM',
 'CM, CDM',
 'CM, CAM',
 'RM, CAM, CM',
 'LB, CB',
 'LW, RW, RM',
 'CDM, CM',
 'CDM, CM',
 'CDM, CM',
 'CDM, CM',
 'CDM, CB',
 'CDM, CM',
 'RB, LB',
 'ST, LW',
 'CM, CDM',
 'CDM, CM',
 'CAM, LM',
 'CDM, CM, CAM',
 'CM, CDM, RM',
 'LWB, LB',
 'CM, CAM',
 'CM, CDM',
 'RM, LM',
 'CM, CDM',
 'CB, RB',
 'LW, RW, CAM',
 'LW, CAM, CM',
 'LB, CB',
 'CAM, CM',
 'CM, CAM',
 'LM, LWB',
 'LW, LM',
 'RM, RW',
 'RB, CB',
 'CM, CDM',
 'CM, CDM',
 'CDM, CM',
 'CM, CDM, CAM',
 'CM, CDM',
 'RB, CDM',
 'LM, ST, RM',
 'CDM, CB',
 'CB, RB',
 'RB, CB',
 'CB, LB',
 'CAM, RM',
 'CDM, CB',
 'CDM, CB, CM',
 'CDM, CM',
 'RB, LB',
 'RB, CB',
 'CAM, CM',
 'LW, RW, LM',
 'LB, LWB',
 'RW, LW, CAM',
 'CF, LW',
 'LM, LW, RM',
 'CM, CAM',
 'CAM, RW',
 'CB, RB',
 'LB, LM',
 'RW, LW',
 'CAM, LW',
 'CDM, CM',
 'RB, LB',
 'RM, ST, CAM',
 'LW, LM',
 'LB, RB',
 'CAM, ST, CF',
 'ST, LW',
 'RM, ST, LM',
 'CDM, CM',
 'RB, RM',
 'CM, CDM',
 'CB, RB',
 'LB, CM, RB',
 'RW, CAM',
 'RW, LW',
 'RB, CB, CDM',
 'CF, ST',
 'ST, CF',
 'CM, CAM, CDM',
 'CAM, LM',
 'CF, ST, CAM',
 'CM, CDM',
 'RB, LB',
 'CB, RB, LB',
 'RB, CB',
 'CM, CDM, CAM',
 'CAM, CM',
 'LM, RM',
 'CAM, RW, RM',
 'CB, RB',
 'RW, LW',
 'RM, CM, CAM',
 'CDM, CM',
 'CAM, LM, RM',
 'ST, CF',
 'RM, LM',
 'CAM, LW',
 'RM, CAM',
 'CAM, CM, CDM',
 'CM, CDM',
 'CAM, CM',
 'LWB, LM',
 'RB, RWB',
 'LW, CF, LM',
 'CM, CDM',
 'LB, LWB',
 'CM, CDM',
 'RM, CAM',
 'LM, CM',
 'CAM, LM',
 'CDM, CM',
 'CAM, CF, CM',
 'LWB, CB',
 'CDM, CM',
 'CM, CDM',
 'ST, CF',
 'CM, CDM',
 'RW, ST',
 'LM, LW, LB',
 'CDM, CM',
 'LM, ST',
 'LB, LWB',
 'CDM, CM',
 'RB, RM',
 'ST, LM',
 'CB, RB',
 'CM, CDM, LW',
 'CDM, CM, CAM',
 'LB, LWB',
 'LM, CM, LB',
 'CM, CDM',
 'CDM, CM',
 'RB, LB',
 'CDM, CM',
 'CB, CDM',
 'LM, RM, CAM',
 'CB, RB, LB',
 'CF, CAM, LW',
 'CM, CAM, RM',
 'RM, RW, ST',
 'CM, CAM',
 'CM, CDM',
 'CAM, RM, CM',
 'CM, RM',
 'CM, CAM',
 'CB, CDM',
 'RW, LW, CF',
 'CM, CDM, CB',
 'LM, CAM',
 'CDM, CM',
 'LM, RM, RW',
 'LM, RM',
 'CM, CDM, CAM',
 'ST, CAM',
 'CDM, CB, CM',
 'CM, CDM, CAM',
 'LM, LWB',
 'CAM, CM',
 'CDM, CM, CB',
 'CAM, ST, LM',
 'CB, LB',
 'RM, RW, LM',
 'RM, RW',
 'RB, LB, RM',
 'CM, CDM',
 'RB, RM, LB',
 'RM, CAM, LM',
 'CB, LB',
 'RB, RM',
 'CDM, CM',
 'CAM, RM',
 'CDM, CM, CB',
 'RWB, RB',
 'LB, LWB',
 'CDM, CM',
 'LWB, RM, LB',
 'LW, RW',
 'RM, LB, RB',
 'CM, CDM',
 'LM, RM',
 'CM, CAM, RM',
 'RB, RWB',
 'CAM, RM',
 'LB, LWB, LM',
 'LM, RM',
 'CB, LB',
 'RM, LM, CAM',
 'ST, CF',
 'ST, RW',
 'RM, RW',
 'CM, CF, RM',
 'ST, CAM',
 'RM, LM',
 'RB, CB',
 'RM, RB, LB',
 'CDM, CM',
 'CAM, LM',
 'CM, CDM',
 'ST, LM, RW',
 'CM, CAM, CDM',
 'LM, CF',
 'RWB, RB, LWB',
 'LM, LB',
 'LW, LM',
 'RB, CB',
 'CM, CAM',
 'CM, CDM',
 'CAM, ST, LW',
 'CB, CDM',
 'RB, RM',
 'CM, CDM',
 'CF, LW, ST',
 ...]

In [24]:
raw[['Height','Weight']]

      Height Weight
0      170cm   72kg
1      187cm   83kg
2      188cm   87kg
3      181cm   70kg
4      175cm   68kg
...      ...    ...
18974  178cm   66kg
18975  175cm   65kg
18976  179cm   74kg
18977  175cm   69kg
18978  188cm   75kg

[18979 rows x 2 columns]

In [25]:
#cleaning Heights column
raw['Height'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [26]:
# Define a function to convert height to meters
def height_to_meters(height):
    if 'cm' in height:
        cm = int(height.replace('cm', '').strip())
        return round(cm / 100, 2)
    else:
        feet, inches = height.split("'")
        total_inches = int(feet) * 12 + int(inches.strip('"'))
        return round(total_inches * 0.0254, 2)

# Create a new column "height (m)"
raw['Height(m)'] = raw['Height'].apply(height_to_meters)

In [27]:
#cleaning Weights column
raw['Weight'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [28]:
#converting lbs to kgs 
# Define a function to convert lbs to kg
def lbs_to_kg(weight):
    if 'lbs' in weight:
        lbs = int(weight.replace('lbs', '').strip())
        return round(lbs * 0.45359237, 1)
    else:
        return int(weight.replace('kg', '').strip())

# Create a new column "weight (kg)"
raw['Weight(kg)'] = raw['Weight'].apply(lbs_to_kg)

In [29]:
raw[['Weight(kg)','Height(m)']]

       Weight(kg)  Height(m)
0            72.0       1.70
1            83.0       1.87
2            87.0       1.88
3            70.0       1.81
4            68.0       1.75
...           ...        ...
18974        66.0       1.78
18975        65.0       1.75
18976        74.0       1.79
18977        69.0       1.75
18978        75.0       1.88

[18979 rows x 2 columns]

In [30]:
#Cleaning Joined column
# extract the date column and convert it to a string format
date_column = raw['Joined'].astype(str)

# get all unique characters from the date column
unique_chars = pd.Series(list(''.join(date_column.unique()))).unique()

print(unique_chars)

['J' 'u' 'l' ' ' '1' ',' '2' '0' '4' '8' '6' 'A' 'g' '3' '5' '7' '9' 'a'
 'n' 'O' 'c' 't' 'S' 'e' 'p' 'M' 'y' 'F' 'b' 'r' 'D' 'N' 'o' 'v']

In [31]:
#Joined column in datetime format
raw['Joined']=pd.to_datetime(raw['Joined'])

In [32]:
#cleaning Loan Date End column
raw['Loan Date End'].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

In [33]:
#Dropping the loan date end column because it doesnt affect the dataset if dropped
raw.drop(['Loan Date End'], axis=1 ,inplace=True)

In [34]:
raw[['Value','Wage','Release Clause']]

         Value   Wage Release Clause
0      €103.5M  €560K        €138.4M
1         €63M  €220K         €75.9M
2        €120M  €125K        €159.4M
3        €129M  €370K          €161M
4        €132M  €270K        €166.5M
...        ...    ...            ...
18974    €100K    €1K           €70K
18975    €130K   €500          €165K
18976    €120K   €500          €131K
18977    €100K    €2K           €88K
18978    €100K    €1K           €79K

[18979 rows x 3 columns]

In [35]:
#Cleaning Value column
raw['Value'].unique()

array(['€103.5M', '€63M', '€120M', '€129M', '€132M', '€111M', '€120.5M',
       '€102M', '€185.5M', '€110M', '€113M', '€90.5M', '€82M', '€17.5M',
       '€83.5M', '€33.5M', '€114.5M', '€78M', '€103M', '€109M', '€92M',
       '€10M', '€76.5M', '€89.5M', '€87.5M', '€79.5M', '€124M', '€114M',
       '€95M', '€92.5M', '€105.5M', '€88.5M', '€85M', '€81.5M', '€26M',
       '€21M', '€56M', '€67.5M', '€53M', '€36.5M', '€51M', '€65.5M',
       '€46.5M', '€61.5M', '€72.5M', '€77.5M', '€43.5M', '€32.5M', '€36M',
       '€32M', '€54M', '€49.5M', '€57M', '€66.5M', '€74.5M', '€71.5M',
       '€121M', '€99M', '€67M', '€86.5M', '€93.5M', '€70M', '€62M',
       '€66M', '€58M', '€44M', '€81M', '€37M', '€14.5M', '€46M', '€47.5M',
       '€52.5M', '€54.5M', '€34.5M', '€57.5M', '€51.5M', '€44.5M', '€55M',
       '€48M', '€60.5M', '€63.5M', '€61M', '€29M', '€58.5M', '€55.5M',
       '€42M', '€40.5M', '€43M', '€45.5M', '€34M', '€26.5M', '€42.5M',
       '€35.5M', '€45M', '€41.5M', '€40M', '€11M', '€13.5M', '€29.5M',
       '€27M', '€15.5M', '€38.5M', '€52M', '€33M', '€19M', '€73.5M',
       '€38M', '€35M', '€47M', '€24M', '€30.5M', '€18M', '€28M', '€25.5M',
       '€25M', '€31M', '€23.5M', '€30M', '€31.5M', '€22.5M', '€28.5M',
       '€4M', '€12.5M', '€37.5M', '€27.5M', '€16M', '€15M', '€20.5M',
       '€22M', '€3.4M', '€5M', '€56.5M', '€62.5M', '€0', '€39M', '€24.5M',
       '€21.5M', '€13M', '€8M', '€20M', '€8.5M', '€2.9M', '€9M', '€4.6M',
       '€50M', '€23M', '€18.5M', '€7M', '€19.5M', '€5.5M', '€7.5M',
       '€3.8M', '€14M', '€10.5M', '€16.5M', '€3.6M', '€9.5M', '€39.5M',
       '€17M', '€12M', '€11.5M', '€4.9M', '€3M', '€1.9M', '€6.5M',
       '€1.7M', '€2.4M', '€3.1M', '€6M', '€3.7M', '€4.7M', '€4.3M',
       '€2.1M', '€1.2M', '€1.8M', '€4.8M', '€3.2M', '€1.3M', '€825K',
       '€2.3M', '€1.5M', '€3.9M', '€2.6M', '€3.5M', '€2.8M', '€2.7M',
       '€4.4M', '€4.1M', '€950K', '€1.6M', '€625K', '€1.1M', '€4.5M',
       '€4.2M', '€2.2M', '€3.3M', '€1.4M', '€2M', '€475K', '€925K',
       '€750K', '€725K', '€2.5M', '€1M', '€350K', '€525K', '€600K',
       '€850K', '€800K', '€550K', '€250K', '€400K', '€425K', '€575K',
       '€210K', '€325K', '€900K', '€875K', '€650K', '€700K', '€500K',
       '€975K', '€375K', '€775K', '€275K', '€180K', '€450K', '€675K',
       '€150K', '€240K', '€300K', '€130K', '€220K', '€200K', '€110K',
       '€170K', '€230K', '€90K', '€120K', '€80K', '€190K', '€140K',
       '€160K', '€100K', '€60K', '€50K', '€70K', '€45K', '€35K', '€40K',
       '€25K', '€20K', '€15K', '€30K', '€9K'], dtype=object)

In [36]:
# remove Euro sign and extract numeric value and unit
raw['Value'] = raw['Value'].str.replace('€', '')
raw[['value', 'unit']] = raw['Value'].str.extract(r'([\d.]+)\s*([a-zA-Z]+)', expand=True)

# convert value to float and multiply by appropriate factor
raw['value'] = raw['value'].astype(float)
raw.loc[raw['unit'] == 'M', 'value'] *= 1000000
raw.loc[raw['unit'] == 'K', 'value'] *= 1000

# remove 'unit' column and update 'Value' column with new values
raw = raw.drop(columns=['unit'])
raw['value'] = raw['value'].fillna(0)  # replace missing values with zero
raw['value'] = np.where(np.isinf(raw['value']), 0, raw['value'])  # replace infinite values with zero
raw['Value'] = raw['value'].astype(int)  # convert to integer data type

In [37]:
raw['Value'].unique()

array([103500000,  63000000, 120000000, 129000000, 132000000, 111000000,
       120500000, 102000000, 185500000, 110000000, 113000000,  90500000,
        82000000,  17500000,  83500000,  33500000, 114500000,  78000000,
       103000000, 109000000,  92000000,  10000000,  76500000,  89500000,
        87500000,  79500000, 124000000, 114000000,  95000000,  92500000,
       105500000,  88500000,  85000000,  81500000,  26000000,  21000000,
        56000000,  67500000,  53000000,  36500000,  51000000,  65500000,
        46500000,  61500000,  72500000,  77500000,  43500000,  32500000,
        36000000,  32000000,  54000000,  49500000,  57000000,  66500000,
        74500000,  71500000, 121000000,  99000000,  67000000,  86500000,
        93500000,  70000000,  62000000,  66000000,  58000000,  44000000,
        81000000,  37000000,  14500000,  46000000,  47500000,  52500000,
        54500000,  34500000,  57500000,  51500000,  44500000,  55000000,
        48000000,  60500000,  63500000,  61000000,  29000000,  58500000,
        55500000,  42000000,  40500000,  43000000,  45500000,  34000000,
        26500000,  42500000,  35500000,  45000000,  41500000,  40000000,
        11000000,  13500000,  29500000,  27000000,  15500000,  38500000,
        52000000,  33000000,  19000000,  73500000,  38000000,  35000000,
        47000000,  24000000,  30500000,  18000000,  28000000,  25500000,
        25000000,  31000000,  23500000,  30000000,  31500000,  22500000,
        28500000,   4000000,  12500000,  37500000,  27500000,  16000000,
        15000000,  20500000,  22000000,   3400000,   5000000,  56500000,
        62500000,         0,  39000000,  24500000,  21500000,  13000000,
         8000000,  20000000,   8500000,   2900000,   9000000,   4600000,
        50000000,  23000000,  18500000,   7000000,  19500000,   5500000,
         7500000,   3800000,  14000000,  10500000,  16500000,   3600000,
         9500000,  39500000,  17000000,  12000000,  11500000,   4900000,
         3000000,   1900000,   6500000,   1700000,   2400000,   3100000,
         6000000,   3700000,   4700000,   4300000,   2100000,   1200000,
         1800000,   4800000,   3200000,   1300000,    825000,   2300000,
         1500000,   3900000,   2600000,   3500000,   2800000,   2700000,
         4400000,   4099999,    950000,   1600000,    625000,   1100000,
         4500000,   4200000,   2200000,   3300000,   1400000,   2000000,
          475000,    925000,    750000,    725000,   2500000,   1000000,
          350000,    525000,    600000,    850000,    800000,    550000,
          250000,    400000,    425000,    575000,    210000,    325000,
          900000,    875000,    650000,    700000,    500000,    975000,
          375000,    775000,    275000,    180000,    450000,    675000,
          150000,    240000,    300000,    130000,    220000,    200000,
          110000,    170000,    230000,     90000,    120000,     80000,
          190000,    140000,    160000,    100000,     60000,     50000,
           70000,     45000,     35000,     40000,     25000,     20000,
           15000,     30000,      9000])

In [38]:
#Cleaning Wage column
raw['Wage'].unique()

array(['€560K', '€220K', '€125K', '€370K', '€270K', '€240K', '€250K',
       '€160K', '€260K', '€210K', '€310K', '€130K', '€350K', '€300K',
       '€190K', '€145K', '€195K', '€100K', '€140K', '€290K', '€82K',
       '€110K', '€230K', '€155K', '€200K', '€165K', '€95K', '€170K',
       '€105K', '€115K', '€150K', '€135K', '€55K', '€58K', '€81K', '€34K',
       '€120K', '€59K', '€90K', '€65K', '€56K', '€71K', '€18K', '€75K',
       '€47K', '€20K', '€84K', '€86K', '€74K', '€78K', '€27K', '€68K',
       '€85K', '€25K', '€46K', '€83K', '€54K', '€79K', '€175K', '€43K',
       '€49K', '€45K', '€38K', '€41K', '€39K', '€23K', '€51K', '€50K',
       '€87K', '€30K', '€14K', '€69K', '€31K', '€64K', '€53K', '€35K',
       '€21K', '€28K', '€17K', '€33K', '€70K', '€32K', '€89K', '€26K',
       '€40K', '€76K', '€72K', '€48K', '€36K', '€29K', '€60K', '€16K',
       '€37K', '€24K', '€52K', '€0', '€62K', '€73K', '€63K', '€19K',
       '€1K', '€66K', '€80K', '€12K', '€2K', '€42K', '€13K', '€900',
       '€57K', '€77K', '€61K', '€22K', '€67K', '€44K', '€15K', '€11K',
       '€8K', '€850', '€10K', '€88K', '€500', '€7K', '€6K', '€9K', '€5K',
       '€700', '€950', '€750', '€3K', '€650', '€600', '€4K', '€800',
       '€550'], dtype=object)

In [39]:
# Remove euro sign and "K" suffix, and convert to integer by multiplying by 1000
raw['Wages(€)'] = [int(wage.strip('€').strip('K'))*1000 if wage[-1] == 'K' else int(wage.strip('€')) for wage in raw['Wage']]

In [40]:
raw['Wages(€)'].unique()

array([560000, 220000, 125000, 370000, 270000, 240000, 250000, 160000,
       260000, 210000, 310000, 130000, 350000, 300000, 190000, 145000,
       195000, 100000, 140000, 290000,  82000, 110000, 230000, 155000,
       200000, 165000,  95000, 170000, 105000, 115000, 150000, 135000,
        55000,  58000,  81000,  34000, 120000,  59000,  90000,  65000,
        56000,  71000,  18000,  75000,  47000,  20000,  84000,  86000,
        74000,  78000,  27000,  68000,  85000,  25000,  46000,  83000,
        54000,  79000, 175000,  43000,  49000,  45000,  38000,  41000,
        39000,  23000,  51000,  50000,  87000,  30000,  14000,  69000,
        31000,  64000,  53000,  35000,  21000,  28000,  17000,  33000,
        70000,  32000,  89000,  26000,  40000,  76000,  72000,  48000,
        36000,  29000,  60000,  16000,  37000,  24000,  52000,      0,
        62000,  73000,  63000,  19000,   1000,  66000,  80000,  12000,
         2000,  42000,  13000,    900,  57000,  77000,  61000,  22000,
        67000,  44000,  15000,  11000,   8000,    850,  10000,  88000,
          500,   7000,   6000,   9000,   5000,    700,    950,    750,
         3000,    650,    600,   4000,    800,    550], dtype=int64)

In [41]:
#cleaning release clause

# remove Euro sign and extract numeric value and unit
raw['Release Clause'] = raw['Release Clause'].str.replace('€', '')
raw[['value', 'unit']] = raw['Release Clause'].str.extract(r'([\d.]+)\s*([a-zA-Z]+)', expand=True)

# convert value to float and multiply by appropriate factor
raw['value'] = raw['value'].astype(float)
raw.loc[raw['unit'] == 'M', 'value'] *= 1000000
raw.loc[raw['unit'] == 'K', 'value'] *= 1000

# remove 'unit' column and update 'Value' column with new values
raw = raw.drop(columns=['unit'])
raw['value'] = raw['value'].fillna(0)  # replace missing values with zero
raw['value'] = np.where(np.isinf(raw['value']), 0, raw['value'])  # replace infinite values with zero
raw['Release_Clause(€)'] = raw['value'].astype(int)  # convert to integer data type

In [42]:
raw['Release_Clause(€)']

0        138400000
1         75900000
2        159400000
3        161000000
4        166500000
           ...
18974        70000
18975       165000
18976       131000
18977        88000
18978        79000
Name: Release_Clause(€), Length: 18979, dtype: int32

In [43]:
raw[['Value','Wages(€)','Release_Clause(€)']]

           Value  Wages(€)  Release_Clause(€)
0      103500000    560000          138400000
1       63000000    220000           75900000
2      120000000    125000          159400000
3      129000000    370000          161000000
4      132000000    270000          166500000
...          ...       ...                ...
18974     100000      1000              70000
18975     130000       500             165000
18976     120000       500             131000
18977     100000      2000              88000
18978     100000      1000              79000

[18979 rows x 3 columns]

In [44]:
raw[['W/F', 'SM', 'IR']]

       W/F  SM   IR
0      4 ★  4★  5 ★
1      4 ★  5★  5 ★
2      3 ★  1★  3 ★
3      5 ★  4★  4 ★
4      5 ★  5★  5 ★
...    ...  ..  ...
18974  2 ★  2★  1 ★
18975  2 ★  2★  1 ★
18976  2 ★  2★  1 ★
18977  3 ★  2★  1 ★
18978  3 ★  2★  1 ★

[18979 rows x 3 columns]

In [45]:
#cleaning W/F column
raw['W/F'].unique()

array(['4 ★', '3 ★', '5 ★', '2 ★', '1 ★'], dtype=object)

In [46]:
raw['W/F rating'] = raw['W/F'].str.extract('(\d+)').astype(int)

In [47]:
#cleaning SM column
raw['SM'].unique()

array(['4★', '5★', '1★', '2★', '3★'], dtype=object)

In [48]:
#similarly like for weak foot column
raw['SM rating'] = raw['SM'].str.extract('(\d+)').astype(int)

In [49]:
#cleaning IR column
raw['IR'].unique()
#similar to previous ones with stars
raw['IR rating'] = raw['IR'].str.extract('(\d+)').astype(int)

In [50]:
raw[['W/F rating','SM rating','IR rating']]

       W/F rating  SM rating  IR rating
0               4          4          5
1               4          5          5
2               3          1          3
3               5          4          4
4               5          5          5
...           ...        ...        ...
18974           2          2          1
18975           2          2          1
18976           2          2          1
18977           3          2          1
18978           3          2          1

[18979 rows x 3 columns]

In [51]:
raw[['Hits']]

      Hits
0      771
1      562
2      150
3      207
4      595
...    ...
18974  NaN
18975  NaN
18976  NaN
18977  NaN
18978  NaN

[18979 rows x 1 columns]

In [52]:
#cleaning hits column
# Convert hits column to string type to avoid errors
raw['Hits'] = raw['Hits'].astype(str)

# Get unique characters from the values column
unique_chars = pd.Series(list(set(''.join(raw['Hits'].unique())))).unique()

# Print the unique characters
print(unique_chars)

['1' '6' '8' 'K' 'n' '.' '3' '9' '5' '0' '7' '4' '2' 'a']

In [53]:
# Define the remove_k_and_convert_to_int() function
def remove_k_and_convert_to_int(value):
    if pd.isna(value):
        return pd.NA
    elif value == '0':
        return 0
    elif 'K' in value:
        value = value.replace('K', '')
        value = float(value) * 1000
        value = int(value)
    else:
        try:
            value = int(value)
        except ValueError:
            value = pd.NA
    return value

raw['Hits'] = raw['Hits'].apply(remove_k_and_convert_to_int).astype('Int64')
# Fill NaN values in 'Hits_int' column with 0
raw['Hits'] = raw['Hits'].fillna(0)

In [54]:
raw[['Hits']]

       Hits
0       771
1       562
2       150
3       207
4       595
...     ...
18974     0
18975     0
18976     0
18977     0
18978     0

[18979 rows x 1 columns]

Done with the objects columns. Now to look at int columns

In [55]:
object_cols

['Name',
 'LongName',
 'photoUrl',
 'playerUrl',
 'Nationality',
 'Club',
 'Contract',
 'Positions',
 'Height',
 'Weight',
 'Preferred Foot',
 'Best Position',
 'Joined',
 'Loan Date End',
 'Value',
 'Wage',
 'Release Clause',
 'W/F',
 'SM',
 'A/W',
 'D/W',
 'IR',
 'Hits']

In [56]:
raw['A/W'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [57]:
raw['W/F rating']=raw['W/F rating'].astype('category')
raw['SM rating']=raw['SM rating'].astype('category')
raw['A/W']=raw['A/W'].astype('category')
raw['D/W']=raw['D/W'].astype('category')
raw['IR rating']=raw['IR rating'].astype('category')
raw['Preferred Foot']=raw['Preferred Foot'].astype('category')

In [58]:
raw.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       'OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Value', 'Wage',
       'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'Player_status', 'Contract_start',
       'Contract_end', 'Contract_Start', 'Height(m)', 'Weight(kg)', 'value',
       'Wages(€)', 'Release_Clause(€)', 'W/F rating', 'SM rating',
       'IR rating'],
      dtype='object')

In [59]:
clean_data=raw.drop(['photoUrl', 'playerUrl','Name','Height', 'Weight', 'Wage','Release Clause','value','W/F', 'SM', 'IR', 'Contract', 'Contract_Start', 'Contract_start','Positions'], axis=1)

In [60]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 73 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 18979 non-null  int64
 1   LongName           18979 non-null  object
 2   Nationality        18979 non-null  object
 3   Age                18979 non-null  int64
 4   OVA                18979 non-null  int64
 5   POT                18979 non-null  int64
 6   Club               18979 non-null  object
 7   Preferred Foot     18979 non-null  category
 8   BOV                18979 non-null  int64
 9   Best Position      18979 non-null  object
 10  Joined             18979 non-null  datetime64[ns]
 11  Value              18979 non-null  int32
 12  Attacking          18979 non-null  int64
 13  Crossing           18979 non-null  int64
 14  Finishing          18979 non-null  int64
 15  Heading Accuracy   18979 non-null  int64
 16  Short Passing      18979 non-null  int64
 17  Volleys            18979 non-null  int64
 18  Skill              18979 non-null  int64
 19  Dribbling          18979 non-null  int64
 20  Curve              18979 non-null  int64
 21  FK Accuracy        18979 non-null  int64
 22  Long Passing       18979 non-null  int64
 23  Ball Control       18979 non-null  int64
 24  Movement           18979 non-null  int64
 25  Acceleration       18979 non-null  int64
 26  Sprint Speed       18979 non-null  int64
 27  Agility            18979 non-null  int64
 28  Reactions          18979 non-null  int64
 29  Balance            18979 non-null  int64
 30  Power              18979 non-null  int64
 31  Shot Power         18979 non-null  int64
 32  Jumping            18979 non-null  int64
 33  Stamina            18979 non-null  int64
 34  Strength           18979 non-null  int64
 35  Long Shots         18979 non-null  int64
 36  Mentality          18979 non-null  int64
 37  Aggression         18979 non-null  int64
 38  Interceptions      18979 non-null  int64
 39  Positioning        18979 non-null  int64
 40  Vision             18979 non-null  int64
 41  Penalties          18979 non-null  int64
 42  Composure          18979 non-null  int64
 43  Defending          18979 non-null  int64
 44  Marking            18979 non-null  int64
 45  Standing Tackle    18979 non-null  int64
 46  Sliding Tackle     18979 non-null  int64
 47  Goalkeeping        18979 non-null  int64
 48  GK Diving          18979 non-null  int64
 49  GK Handling        18979 non-null  int64
 50  GK Kicking         18979 non-null  int64
 51  GK Positioning     18979 non-null  int64
 52  GK Reflexes        18979 non-null  int64
 53  Total Stats        18979 non-null  int64
 54  Base Stats         18979 non-null  int64
 55  A/W                18979 non-null  category
 56  D/W                18979 non-null  category
 57  PAC                18979 non-null  int64
 58  SHO                18979 non-null  int64
 59  PAS                18979 non-null  int64
 60  DRI                18979 non-null  int64
 61  DEF                18979 non-null  int64
 62  PHY                18979 non-null  int64
 63  Hits               18979 non-null  Int64
 64  Player_status      18979 non-null  object
 65  Contract_end       18742 non-null  object
 66  Height(m)          18979 non-null  float64
 67  Weight(kg)         18979 non-null  float64
 68  Wages(€)           18979 non-null  int64
 69  Release_Clause(€)  18979 non-null  int32
 70  W/F rating         18979 non-null  category
 71  SM rating          18979 non-null  category
 72  IR rating          18979 non-null  category
dtypes: Int64(1), category(6), datetime64[ns](1), float64(2), int32(2), int64(55), object(6)
memory usage: 9.7+ MB

In [61]:
#Exporting for further analysis
clean_data.to_excel('fifa_clean_data.xlsx',index=False)